export const MATRIX_EDIT_ALLOW_COMBINATION = 'MATRIX_EDIT_ALLOW_COMBINATION';

export const MATRIX_EDIT_DENY_COMBINATION = 'MATRIX_EDIT_DENY_COMBINATION';

export const MATRIX_EDIT_COUNTRY_CHANGE = 'MATRIX_EDIT_COUNTRY_CHANGE';