export const fakeCountries = [
    { id: "1", name: "Algeria" },
    { id: "2", name: "Tunisia" },
    { id: "3", name: "Switzerland" },
    { id: "4", name: "Sweden" },
    { id: "5", name: "Spain" },
    { id: "6", name: "South Africa" },
    { id: "7", name: "Portugal" },
    { id: "8", name: "Poland" },
    { id: "9", name: "Norway" },
    { id: "10", name: "Netherlands" },
    { id: "11", name: "Morocco" },
    { id: "12", name: "Middle East" },
    { id: "13", name: "Luxembourg" },
    { id: "14", name: "Japan" },
    { id: "15", name: "Italy" },
    { id: "16", name: "India" },
    { id: "17", name: "Hungary" },
    { id: "18", name: "Greece" },
    { id: "19", name: "Germany" },
    { id: "20", name: "France" },
    { id: "21", name: "Finland" },
    { id: "22", name: "Egypt" },
    { id: "23", name: "Denmark" },
    { id: "24", name: "Czech Republic" },
    { id: "25", name: "CIS & Russia" },
    { id: "26", name: "Belgium" },
    { id: "27", name: "Balkans" },
    { id: "28", name: "Austria" },
    { id: "29", name: "Turkey" },
    { id: "30", name: "UK & Ireland" }
];