//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.Import.Por.Core.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCD2_LUT_TSP
    {
        public string Country_Group { get; set; }
        public string Service_Code { get; set; }
        public string Description { get; set; }
        public string Scope { get; set; }
        public string Start_Date { get; set; }
        public string Warranty_Group { get; set; }
    }
}
