//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.Import.Por.Core.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCD2_SW_Overview
    {
        public string WG { get; set; }
        public string WG_Definition { get; set; }
        public string PLA { get; set; }
        public string Software_Lizenz_Digit { get; set; }
        public string Software_Lizenz_Beschreibung { get; set; }
        public string Service_Code { get; set; }
        public string Service_Description { get; set; }
        public string Service_Code_Requester { get; set; }
        public string Software_Lizenz { get; set; }
        public string Software_Lizenz_Benennung { get; set; }
        public string Service_Code_Status { get; set; }
        public string Service_Short_Description { get; set; }
        public string Proactive { get; set; }
        public string SCD_Relevant { get; set; }
        public int ID { get; set; }
        public string SOG_Code { get; set; }
        public string SOG { get; set; }
        public string ServiceFabGrp { get; set; }
        public string SCD_ServiceType { get; set; }
    }
}
