//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.Import.Por.Core.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCD2_v_SAR_new_codes
    {
        public string Service_Code { get; set; }
        public string Country { get; set; }
        public string WG { get; set; }
        public string SOG { get; set; }
        public string ServiceType { get; set; }
        public string Response_Recovery { get; set; }
        public string BusinessHours { get; set; }
        public string SecondSLA { get; set; }
        public string SAP_Kurztext_Englisch { get; set; }
        public string Duration { get; set; }
        public string Servicelevel { get; set; }
        public string VStatus { get; set; }
        public string EKSchluesselSAP { get; set; }
        public string MaxSpares { get; set; }
        public string EKSchluessel { get; set; }
        public string Project { get; set; }
        public string SCD_ServiceType { get; set; }
        public string Atom_Location { get; set; }
        public string Atom_R_Type { get; set; }
        public string Atom_R_Time { get; set; }
        public string Atom_Availability { get; set; }
        public string Atom_Duration { get; set; }
        public string Item_Category { get; set; }
    }
}
