//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.Import.Por.Core.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCD2_SWR_Level
    {
        public string ID { get; set; }
        public string Beschreibung { get; set; }
        public string Proactive { get; set; }
        public string Servicelevel { get; set; }
        public string SW_level_digit_ReactiveMapping { get; set; }
    }
}
