ALTER DATABASE SCD_2 SET RECOVERY SIMPLE
GO 

ALTER INDEX IX_PrincipalPortfolio_AvailabilityId    ON Portfolio.PrincipalPortfolio DISABLE;  
ALTER INDEX IX_PrincipalPortfolio_DurationId        ON Portfolio.PrincipalPortfolio DISABLE;  
ALTER INDEX IX_PrincipalPortfolio_ReactionTimeId    ON Portfolio.PrincipalPortfolio DISABLE;  
ALTER INDEX IX_PrincipalPortfolio_ReactionTypeId    ON Portfolio.PrincipalPortfolio DISABLE;  
ALTER INDEX IX_PrincipalPortfolio_ServiceLocationId ON Portfolio.PrincipalPortfolio DISABLE;  
ALTER INDEX IX_PrincipalPortfolio_WgId              ON Portfolio.PrincipalPortfolio DISABLE;  
ALTER INDEX IX_PrincipalPortfolio_ProActiveSlaId    ON Portfolio.PrincipalPortfolio DISABLE;  

-- Disable all table constraints
ALTER TABLE Portfolio.PrincipalPortfolio NOCHECK CONSTRAINT ALL

GO

truncate table Portfolio.PrincipalPortfolio;

GO

with PortfolioCte as (
    select *
    from (values
              (('DP1'), ('9X5'), ('NONE'), ('NONE'), ('BRING-IN'), ('-'))
            , (('DP1'), ('9X5'), ('NONE'), ('NONE'), ('COLLECT & RETURN'), ('-'))
            , (('DP1'), ('9X5'), ('NONE'), ('NONE'), ('DOOR-TO-DOOR EXCHANGE'), ('-'))
            , (('DP1'), ('9X5'), ('NONE'), ('NONE'), ('DESK-TO-DESK EXCHANGE'), ('-'))
            , (('DP1'), ('9X5'), ('SBD'), ('RESPONSE'), ('DESK-TO-DESK EXCHANGE'), ('-'))
            , (('DP1'), ('9X5'), ('NBD'), ('RESPONSE'), ('DESK-TO-DESK EXCHANGE'), ('-'))
            , (('DP2'), ('9X5'), ('NONE'), ('NONE'), ('BRING-IN'), ('-'))
            , (('DP2'), ('9X5'), ('NONE'), ('NONE'), ('COLLECT & RETURN'), ('-'))
            , (('DP2'), ('9X5'), ('NONE'), ('NONE'), ('DOOR-TO-DOOR EXCHANGE'), ('-'))
            , (('DP2'), ('9X5'), ('NONE'), ('NONE'), ('DESK-TO-DESK EXCHANGE'), ('-'))
            , (('DP2'), ('9X5'), ('SBD'), ('RESPONSE'), ('DESK-TO-DESK EXCHANGE'), ('-'))
            , (('DP2'), ('9X5'), ('NBD'), ('RESPONSE'), ('DESK-TO-DESK EXCHANGE'), ('-'))
            , (('DT1'), ('9X5'), ('NONE'), ('NONE'), ('BRING-IN'), ('-'))
            , (('DT1'), ('9X5'), ('NONE'), ('NONE'), ('COLLECT & RETURN'), ('-'))
            , (('DT1'), ('9X5'), ('NONE'), ('NONE'), ('SEND-IN/RETURN-TO-BASE SERVICE'), ('-'))
            , (('DT1'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('DT1'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('DT1'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('DT1'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('DT1'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('DT2'), ('9X5'), ('NONE'), ('NONE'), ('BRING-IN'), ('-'))
            , (('DT2'), ('9X5'), ('NONE'), ('NONE'), ('COLLECT & RETURN'), ('-'))
            , (('DT2'), ('9X5'), ('NONE'), ('NONE'), ('SEND-IN/RETURN-TO-BASE SERVICE'), ('-'))
            , (('DT2'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('DT2'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('DT2'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('DT2'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('DT2'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('DT3'), ('9X5'), ('NONE'), ('NONE'), ('BRING-IN'), ('-'))
            , (('DT3'), ('9X5'), ('NONE'), ('NONE'), ('COLLECT & RETURN'), ('-'))
            , (('DT3'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE EXCHANGE'), ('-'))
            , (('DT4'), ('9X5'), ('NONE'), ('NONE'), ('BRING-IN'), ('-'))
            , (('DT4'), ('9X5'), ('NONE'), ('NONE'), ('COLLECT & RETURN'), ('-'))
            , (('DT4'), ('9X5'), ('NONE'), ('NONE'), ('SEND-IN/RETURN-TO-BASE SERVICE'), ('-'))
            , (('DT4'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('DT4'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('DT4'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('DT4'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('DT4'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('DT5'), ('9X5'), ('NONE'), ('NONE'), ('BRING-IN'), ('-'))
            , (('DT5'), ('9X5'), ('NONE'), ('NONE'), ('COLLECT & RETURN'), ('-'))
            , (('DT5'), ('9X5'), ('NONE'), ('NONE'), ('SEND-IN/RETURN-TO-BASE SERVICE'), ('-'))
            , (('DT5'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('DT5'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('DT5'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('DT5'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('DT5'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('DT6'), ('9X5'), ('NONE'), ('NONE'), ('BRING-IN'), ('-'))
            , (('DT6'), ('9X5'), ('NONE'), ('NONE'), ('COLLECT & RETURN'), ('-'))
            , (('DT6'), ('9X5'), ('NONE'), ('NONE'), ('SEND-IN/RETURN-TO-BASE SERVICE'), ('-'))
            , (('DT6'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('DT6'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('DT6'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('DT6'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('DT6'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('DT7'), ('9X5'), ('NONE'), ('NONE'), ('BRING-IN'), ('-'))
            , (('DT7'), ('9X5'), ('NONE'), ('NONE'), ('COLLECT & RETURN'), ('-'))
            , (('DT7'), ('9X5'), ('NONE'), ('NONE'), ('SEND-IN/RETURN-TO-BASE SERVICE'), ('-'))
            , (('DT7'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('DT7'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('DT7'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('DT7'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('DT7'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('IOT'), ('9X5'), ('NONE'), ('NONE'), ('BRING-IN'), ('-'))
            , (('IOT'), ('9X5'), ('NONE'), ('NONE'), ('COLLECT & RETURN'), ('-'))
            , (('IOT'), ('9X5'), ('NONE'), ('NONE'), ('DOOR-TO-DOOR EXCHANGE'), ('-'))
            , (('IOT'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE EXCHANGE'), ('-'))
            , (('IOT'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE EXCHANGE'), ('-'))
            , (('IOT'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE EXCHANGE'), ('-'))
            , (('IOT'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE EXCHANGE'), ('-'))
            , (('MB0'), ('9X5'), ('NONE'), ('NONE'), ('BRING-IN'), ('-'))
            , (('MB0'), ('9X5'), ('NONE'), ('NONE'), ('COLLECT & RETURN'), ('-'))
            , (('MB0'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE EXCHANGE'), ('-'))
            , (('MB1'), ('9X5'), ('NONE'), ('NONE'), ('BRING-IN'), ('-'))
            , (('MB1'), ('9X5'), ('NONE'), ('NONE'), ('COLLECT & RETURN'), ('-'))
            , (('MB1'), ('9X5'), ('NONE'), ('NONE'), ('SEND-IN/RETURN-TO-BASE SERVICE'), ('-'))
            , (('MB1'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('MB1'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('MB1'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('MB1'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('MB1'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('MB2'), ('9X5'), ('NONE'), ('NONE'), ('BRING-IN'), ('-'))
            , (('MB2'), ('9X5'), ('NONE'), ('NONE'), ('COLLECT & RETURN'), ('-'))
            , (('MB2'), ('9X5'), ('NONE'), ('NONE'), ('SEND-IN/RETURN-TO-BASE SERVICE'), ('-'))
            , (('MB2'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('MB2'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('MB2'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('MB2'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('MB2'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('MB3'), ('9X5'), ('NONE'), ('NONE'), ('BRING-IN'), ('-'))
            , (('MB3'), ('9X5'), ('NONE'), ('NONE'), ('COLLECT & RETURN'), ('-'))
            , (('MB3'), ('9X5'), ('NONE'), ('NONE'), ('SEND-IN/RETURN-TO-BASE SERVICE'), ('-'))
            , (('MB3'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('MB3'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('MB3'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('MB3'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('MB3'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('MB4'), ('9X5'), ('NONE'), ('NONE'), ('BRING-IN'), ('-'))
            , (('MB4'), ('9X5'), ('NONE'), ('NONE'), ('COLLECT & RETURN'), ('-'))
            , (('MB4'), ('9X5'), ('NONE'), ('NONE'), ('SEND-IN/RETURN-TO-BASE SERVICE'), ('-'))
            , (('MB4'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('MB4'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('MB4'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('MB4'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('MB4'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('P1S'), ('9X5'), ('NONE'), ('NONE'), ('BRING-IN'), ('-'))
            , (('P1S'), ('9X5'), ('NONE'), ('NONE'), ('COLLECT & RETURN'), ('-'))
            , (('P1S'), ('9X5'), ('NONE'), ('NONE'), ('DOOR-TO-DOOR EXCHANGE'), ('-'))
            , (('P1S'), ('9X5'), ('NONE'), ('NONE'), ('SEND-IN/RETURN-TO-BASE SERVICE'), ('-'))
            , (('P1S'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE EXCHANGE'), ('-'))
            , (('P1S'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE EXCHANGE'), ('-'))
            , (('P1S'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE EXCHANGE'), ('-'))
            , (('P1S'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE EXCHANGE'), ('-'))
            , (('P2S'), ('9X5'), ('NONE'), ('NONE'), ('BRING-IN'), ('-'))
            , (('P2S'), ('9X5'), ('NONE'), ('NONE'), ('DOOR-TO-DOOR EXCHANGE'), ('-'))
            , (('P2S'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE EXCHANGE'), ('-'))
            , (('P2S'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE EXCHANGE'), ('-'))
            , (('P2S'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE EXCHANGE'), ('-'))
            , (('P2S'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE EXCHANGE'), ('-'))
            , (('R0A'), ('9X5'), ('NONE'), ('NONE'), ('COLLECT & RETURN'), ('-'))
            , (('R0A'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0A'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0A'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0C'), ('9X5'), ('NONE'), ('NONE'), ('COLLECT & RETURN'), ('-'))
            , (('R0C'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0C'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0C'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0D'), ('9X5'), ('NONE'), ('NONE'), ('COLLECT & RETURN'), ('-'))
            , (('R0D'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0D'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0D'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0E'), ('9X5'), ('NONE'), ('NONE'), ('COLLECT & RETURN'), ('-'))
            , (('R0E'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0E'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0E'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0F'), ('9X5'), ('NONE'), ('NONE'), ('COLLECT & RETURN'), ('-'))
            , (('R0F'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0F'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0F'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0F'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE EXCHANGE'), ('-'))
            , (('R0F'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE EXCHANGE'), ('-'))
            , (('R0G'), ('9X5'), ('NONE'), ('NONE'), ('COLLECT & RETURN'), ('-'))
            , (('R0G'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0G'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0G'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0G'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE EXCHANGE'), ('-'))
            , (('R0G'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE EXCHANGE'), ('-'))
            , (('R0H'), ('9X5'), ('NONE'), ('NONE'), ('COLLECT & RETURN'), ('-'))
            , (('R0H'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0H'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0H'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0H'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE EXCHANGE'), ('-'))
            , (('R0H'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE EXCHANGE'), ('-'))
            , (('R0I'), ('9X5'), ('NONE'), ('NONE'), ('COLLECT & RETURN'), ('-'))
            , (('R0I'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0I'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0I'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0I'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE EXCHANGE'), ('-'))
            , (('R0I'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE EXCHANGE'), ('-'))
            , (('R0J'), ('9X5'), ('NONE'), ('NONE'), ('COLLECT & RETURN'), ('-'))
            , (('R0J'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0J'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0J'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0J'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE EXCHANGE'), ('-'))
            , (('R0J'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE EXCHANGE'), ('-'))
            , (('R0K'), ('9X5'), ('NONE'), ('NONE'), ('COLLECT & RETURN'), ('-'))
            , (('R0K'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0K'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0K'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0K'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE EXCHANGE'), ('-'))
            , (('R0K'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE EXCHANGE'), ('-'))
            , (('R0L'), ('9X5'), ('NONE'), ('NONE'), ('COLLECT & RETURN'), ('-'))
            , (('R0L'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0L'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0L'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0L'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE EXCHANGE'), ('-'))
            , (('R0L'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE EXCHANGE'), ('-'))
            , (('R0M'), ('9X5'), ('NONE'), ('NONE'), ('COLLECT & RETURN'), ('-'))
            , (('R0M'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0M'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0M'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0M'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE EXCHANGE'), ('-'))
            , (('R0M'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE EXCHANGE'), ('-'))
            , (('R0N'), ('9X5'), ('NONE'), ('NONE'), ('COLLECT & RETURN'), ('-'))
            , (('R0N'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0N'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0N'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0N'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE EXCHANGE'), ('-'))
            , (('R0N'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE EXCHANGE'), ('-'))
            , (('R0O'), ('9X5'), ('NONE'), ('NONE'), ('COLLECT & RETURN'), ('-'))
            , (('R0O'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0O'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0O'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0O'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE EXCHANGE'), ('-'))
            , (('R0O'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE EXCHANGE'), ('-'))
            , (('R0P'), ('9X5'), ('NONE'), ('NONE'), ('COLLECT & RETURN'), ('-'))
            , (('R0P'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0P'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0P'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0P'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE EXCHANGE'), ('-'))
            , (('R0P'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE EXCHANGE'), ('-'))
            , (('R0Q'), ('9X5'), ('NONE'), ('NONE'), ('COLLECT & RETURN'), ('-'))
            , (('R0Q'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0Q'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0Q'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0Q'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE EXCHANGE'), ('-'))
            , (('R0Q'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE EXCHANGE'), ('-'))
            , (('R0R'), ('9X5'), ('NONE'), ('NONE'), ('COLLECT & RETURN'), ('-'))
            , (('R0R'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0R'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0R'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0R'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE EXCHANGE'), ('-'))
            , (('R0R'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE EXCHANGE'), ('-'))
            , (('R0S'), ('9X5'), ('NONE'), ('NONE'), ('COLLECT & RETURN'), ('-'))
            , (('R0S'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0S'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0S'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0S'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE EXCHANGE'), ('-'))
            , (('R0S'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE EXCHANGE'), ('-'))
            , (('R0T'), ('9X5'), ('NONE'), ('NONE'), ('COLLECT & RETURN'), ('-'))
            , (('R0T'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0T'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0T'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0T'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE EXCHANGE'), ('-'))
            , (('R0T'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE EXCHANGE'), ('-'))
            , (('R0U'), ('9X5'), ('NONE'), ('NONE'), ('COLLECT & RETURN'), ('-'))
            , (('R0U'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0U'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0U'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0U'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE EXCHANGE'), ('-'))
            , (('R0U'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE EXCHANGE'), ('-'))
            , (('R0V'), ('9X5'), ('NONE'), ('NONE'), ('COLLECT & RETURN'), ('-'))
            , (('R0V'), ('9X5'), ('NONE'), ('NONE'), ('SEND-IN/RETURN-TO-BASE SERVICE'), ('-'))
            , (('R0V'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0W'), ('9X5'), ('NONE'), ('NONE'), ('COLLECT & RETURN'), ('-'))
            , (('R0W'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0W'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0W'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0X'), ('9X5'), ('NONE'), ('NONE'), ('COLLECT & RETURN'), ('-'))
            , (('R0X'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0X'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0X'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0Y'), ('9X5'), ('NONE'), ('NONE'), ('COLLECT & RETURN'), ('-'))
            , (('R0Y'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0Y'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0Y'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('R0Y'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE EXCHANGE'), ('-'))
            , (('R0Y'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE EXCHANGE'), ('-'))
            , (('S2A'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('S2A'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('S2A'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('S2A'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('S2A'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('S2A'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('S2A'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('S2A'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('S2A'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('S2A'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('S2A'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('S2A'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('S2A'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('S2A'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('S2A'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('S2A'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('S2A'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('S2A'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('S2A'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('S2A'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('S2A'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('S2A'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('S2A'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('S2A'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('S2A'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('S2A'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('S2A'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('S2A'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('S2A'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('S2A'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('S2B'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('S2B'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('S2B'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('S2B'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('S2B'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('S2B'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('S2B'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('S2B'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('S2B'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('S2B'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('S2B'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('S2B'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('S2B'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('S2B'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('S2B'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('S2B'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('S2B'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('S2B'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('S2B'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('S2B'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('S2B'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('S2B'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('S2B'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('S2B'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('S2B'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('S2B'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('S2B'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('S2B'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('S2B'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('S2B'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('S2C'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('S2C'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('S2C'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('S2C'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('S2C'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('S2C'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('S2C'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('S2C'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('S2C'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('S8A'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('S8A'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('S8A'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('S8A'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('S8A'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('S8A'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('S8A'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('S8A'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('S8A'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('S8A'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('S8A'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('S8A'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('S8A'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('S8A'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('S8A'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('S8A'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('S8A'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('S8A'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('S8A'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('S8A'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('S8A'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('S8A'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('S8A'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('S8A'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('S8A'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('S8A'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('S8A'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('S8A'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('S8A'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('S8A'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('S8B'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('S8B'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('S8B'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('S8B'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('S8B'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('S8B'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('S8B'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('S8B'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('S8B'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('S8B'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('S8B'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('S8B'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('S8B'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('S8B'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('S8B'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('S8B'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('S8B'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('S8B'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('S8B'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('S8B'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('S8B'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('S8B'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('S8B'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('S8B'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('S8B'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('S8B'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('S8B'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('S8B'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('S8B'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('S8B'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('S8C'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('S8C'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('S8C'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('S8C'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('S8C'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('S8C'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('S8C'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('S8C'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('S8C'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('S8C'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('S8C'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('S8C'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('S8C'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('S8C'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('S8C'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('S8C'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('S8C'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('S8C'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('S8C'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('S8C'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('S8C'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('S8C'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('S8C'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('S8C'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('S8C'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('S8C'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('S8C'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('S8C'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('S8C'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('S8C'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('S8D'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('S8D'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('S8D'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('S8D'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('S8D'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('S8D'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('S8D'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('S8D'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('S8D'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('S8D'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('S8D'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('S8D'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('S8D'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('S8D'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('S8D'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('S8D'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('S8D'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('S8D'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('S8D'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('S8D'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('S8D'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('S8D'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('S8D'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('S8D'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('S8D'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('S8D'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('S8D'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('S8D'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('S8D'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('S8D'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('S9B'), ('9X5'), ('NONE'), ('NONE'), ('BRING-IN'), ('-'))
            , (('S9B'), ('9X5'), ('NONE'), ('NONE'), ('COLLECT & RETURN'), ('-'))
            , (('S9B'), ('9X5'), ('NONE'), ('NONE'), ('SEND-IN/RETURN-TO-BASE SERVICE'), ('-'))
            , (('S9B'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('S9B'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('S9B'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('S9B'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('S9B'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('S9C'), ('9X5'), ('NONE'), ('NONE'), ('BRING-IN'), ('-'))
            , (('S9C'), ('9X5'), ('NONE'), ('NONE'), ('COLLECT & RETURN'), ('-'))
            , (('S9C'), ('9X5'), ('NONE'), ('NONE'), ('SEND-IN/RETURN-TO-BASE SERVICE'), ('-'))
            , (('S9C'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('S9C'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('S9C'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('S9C'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('S9C'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('ST0'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST0'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST0'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST0'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST0'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST0'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('ST0'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('ST0'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('ST0'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('ST0'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('ST0'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('ST0'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('ST0'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('ST0'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('ST0'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('ST0'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('ST0'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('ST0'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('ST0'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('ST0'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('ST0'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('ST0'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('ST0'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('ST0'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('ST0'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('ST0'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('ST0'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('ST0'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('ST0'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('ST0'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('ST1'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST1'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST1'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST1'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST1'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST1'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('ST1'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('ST1'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('ST1'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('ST1'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('ST1'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('ST1'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('ST1'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('ST1'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('ST1'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('ST1'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('ST1'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('ST1'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('ST1'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('ST1'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('ST1'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('ST1'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('ST1'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('ST1'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('ST1'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('ST1'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('ST1'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('ST1'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('ST1'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('ST1'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('ST2'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST2'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST2'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST2'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST2'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST2'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('ST2'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('ST2'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('ST2'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('ST2'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('ST2'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('ST2'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('ST2'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('ST2'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('ST2'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('ST2'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('ST2'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('ST2'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('ST2'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('ST2'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('ST2'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('ST2'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('ST2'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('ST2'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('ST2'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('ST2'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('ST2'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('ST2'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('ST2'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('ST2'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('ST3'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST3'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST3'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST3'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST3'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST3'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('ST3'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('ST3'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('ST3'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('ST3'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('ST3'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('ST3'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('ST3'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('ST3'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('ST3'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('ST3'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('ST3'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('ST3'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('ST3'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('ST3'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('ST3'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('ST3'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('ST3'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('ST3'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('ST3'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('ST3'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('ST3'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('ST3'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('ST3'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('ST3'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('ST4'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST4'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST4'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST4'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST4'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST4'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('ST4'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('ST4'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('ST4'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('ST4'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('ST4'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('ST4'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('ST4'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('ST4'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('ST4'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('ST4'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('ST4'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('ST4'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('ST4'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('ST4'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('ST4'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('ST4'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('ST4'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('ST4'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('ST4'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('ST4'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('ST4'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('ST4'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('ST4'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('ST4'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('ST5'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST5'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST5'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST5'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST5'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST5'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('ST5'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('ST5'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('ST5'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('ST5'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('ST5'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('ST5'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('ST5'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('ST5'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('ST5'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('ST5'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('ST5'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('ST5'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('ST5'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('ST5'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('ST5'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('ST5'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('ST5'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('ST5'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('ST5'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('ST5'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('ST5'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('ST5'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('ST5'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('ST5'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('ST6'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST6'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST6'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST6'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST6'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST6'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('ST6'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('ST6'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('ST6'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('ST7'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST7'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST7'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST7'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST7'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST7'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('ST7'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('ST7'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('ST7'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STB'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('STB'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STB'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STB'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STB'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STB'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STB'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STB'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STB'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STC'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('STC'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STC'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STC'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STC'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STC'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STC'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STC'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STC'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STD'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('STD'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STD'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STD'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STD'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STD'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STD'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STD'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STD'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STE'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('STE'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STE'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STE'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STE'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STE'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STE'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STE'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STE'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STF'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('STF'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STF'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STF'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STF'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STF'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STF'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STF'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STF'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STG'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('STG'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STG'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STG'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STG'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STG'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STG'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STG'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STG'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STH'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('STH'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STH'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STH'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STH'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STH'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STH'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STH'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STH'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STI'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('STI'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STI'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STI'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STI'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STI'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STI'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STI'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STI'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STJ'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('STJ'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STJ'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STJ'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STJ'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STJ'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STJ'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STJ'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STJ'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STK'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('STK'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STK'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STK'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STK'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STK'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STK'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STK'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STK'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STL'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('STL'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STL'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STL'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STL'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STL'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STL'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STL'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STL'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STQ'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('STQ'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STQ'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STQ'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STQ'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STQ'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STQ'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STQ'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STQ'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STR'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('STR'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STR'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STR'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STR'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STR'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STR'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STR'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STR'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STS'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('STS'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STS'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STS'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STS'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STS'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STS'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STS'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STS'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STT'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('STT'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STT'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STT'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STT'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('STT'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STT'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STT'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('STT'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('SV0'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('SV0'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('SV0'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('SV0'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('SV0'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('SV0'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('SV0'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('SV0'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('SV0'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('SV1'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('SV1'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('SV1'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('SV1'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('SV1'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('SV1'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('SV1'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('SV1'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('SV1'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('SV1'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('SV1'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('SV1'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('SV1'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('SV1'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('SV1'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('SV1'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('SV1'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('SV1'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('SV1'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('SV1'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('SV1'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('SV1'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('SV1'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('SV1'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('SV1'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('SV1'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('SV1'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('SV1'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('SV1'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('SV1'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('SV2'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('SV2'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('SV2'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('SV2'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('SV2'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('SV2'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('SV2'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('SV2'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('SV2'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('SV2'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('SV2'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('SV2'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('SV2'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('SV2'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('SV2'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('SV2'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('SV2'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('SV2'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('SV2'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('SV2'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('SV2'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('SV2'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('SV2'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('SV2'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('SV2'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('SV2'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('SV2'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('SV2'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('SV2'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('SV2'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('SV3'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('SV3'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('SV3'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('SV3'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('SV3'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('SV3'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('SV3'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('SV3'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('SV3'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('SV4'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('SV4'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('SV4'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('SV4'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('SV4'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('SV4'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('SV4'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('SV4'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('SV4'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('SV4'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('SV4'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('SV4'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('SV4'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('SV4'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('SV4'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('SV4'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('SV4'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('SV4'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('SV4'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('SV4'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('SV4'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('SV4'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('SV4'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('SV4'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('SV4'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('SV4'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('SV4'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('SV4'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('SV4'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('SV4'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('SV5'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('SV5'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('SV5'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('SV5'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('SV5'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('SV5'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('SV5'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('SV5'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('SV5'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('SV6'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('SV6'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('SV6'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('SV6'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('SV6'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('SV6'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('SV6'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('SV6'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('SV6'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('SVQ'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('SVQ'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('SVQ'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('SVQ'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('SVQ'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('SVQ'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('SVQ'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('SVQ'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('SVQ'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('SVQ'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('SVQ'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('SVQ'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('SVQ'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('SVQ'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('SVQ'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('SVQ'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('SVQ'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('SVQ'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('SVQ'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('SVQ'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('SVQ'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('SVQ'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('SVQ'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('SVQ'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('SVQ'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('SVQ'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('SVQ'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('SVQ'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('SVQ'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('SVQ'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('V1S'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('V1S'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('V1S'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('V1S'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('V1S'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('V1S'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('V1S'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('V1S'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('V1S'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('ST8'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST8'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST8'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST8'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST8'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST8'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('ST8'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('ST8'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('ST8'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('ST9'), ('9X5'), ('NONE'), ('NONE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST9'), ('9X5'), ('SBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST9'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST9'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST9'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('-'))
            , (('ST9'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('ST9'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('ST9'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('ST9'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('2'))
            , (('ST9'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('ST9'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('ST9'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('2'))
            , (('ST9'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('ST9'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('ST9'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('ST9'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('3'))
            , (('ST9'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('ST9'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('ST9'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('3'))
            , (('ST9'), ('9X5'), ('NBD'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('ST9'), ('9X5'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('ST9'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('ST9'), ('24X7'), ('4H'), ('RESPONSE'), ('ON-SITE SERVICE'), ('4'))
            , (('ST9'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('ST9'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('ST9'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('4'))
            , (('ST9'), ('9X5'), ('NBD'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('ST9'), ('24X7'), ('24H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('ST9'), ('24X7'), ('8H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
            , (('ST9'), ('24X7'), ('4H'), ('RECOVERY'), ('ON-SITE SERVICE'), ('-'))
        ) as sla(sog, av, rtime, rtype, loc, pro)
)
, SlaCte as (
    select sog.Id as SogId
         , wg.Id as WgId
         , av.id as AvailabilityId
         , rtype.Id as ReactionTypeId
         , rtime.Id as ReactionTimeId
         , loc.Id as ServiceLocationId
         , pro.Id as ProActiveSlaId
    from PortfolioCte p
    left join InputAtoms.Sog sog on UPPER(sog.Name) = UPPER(p.sog)
    left join InputAtoms.Wg wg on sog.Id = wg.SogId
    left join Dependencies.Availability av on UPPER(av.Name) = UPPER(p.av)
    left join Dependencies.ReactionType rtype on UPPER(rtype.ExternalName) = UPPER(p.rtype)
    left join Dependencies.ReactionTime rtime on UPPER(rtime.ExternalName) = UPPER(p.rtime)
    left join Dependencies.ServiceLocation loc on UPPER(loc.ExternalName) = UPPER(p.loc)
    left join Dependencies.ProActiveSla pro on UPPER(pro.Name) = upper(p.pro)
)
insert into Portfolio.PrincipalPortfolio(
                WgId
              , AvailabilityId
              , DurationId
              , ReactionTimeId
              , ReactionTypeId
              , ServiceLocationId
              , ProActiveSlaId
              , IsGlobalPortfolio
              , IsMasterPortfolio
              , IsCorePortfolio
            )
    select sla.WgId, sla.AvailabilityId, dur.Id, sla.ReactionTimeId, sla.ReactionTypeId, sla.ServiceLocationId, sla.ProActiveSlaId, 1, 0, 0
    from SlaCte sla
        , Dependencies.Duration dur
    where (dur.IsProlongation = 0 and dur.Value in (3,4,5)) or (dur.IsProlongation = 1 and dur.Value = 1);

ALTER INDEX IX_PrincipalPortfolio_AvailabilityId ON Portfolio.PrincipalPortfolio REBUILD;  

GO

ALTER INDEX IX_PrincipalPortfolio_DurationId ON Portfolio.PrincipalPortfolio REBUILD;  

GO

ALTER INDEX IX_PrincipalPortfolio_ReactionTimeId ON Portfolio.PrincipalPortfolio REBUILD;  

GO

ALTER INDEX IX_PrincipalPortfolio_ReactionTypeId ON Portfolio.PrincipalPortfolio REBUILD;  

GO

ALTER INDEX IX_PrincipalPortfolio_ServiceLocationId ON Portfolio.PrincipalPortfolio REBUILD;  

GO

ALTER INDEX IX_PrincipalPortfolio_WgId ON Portfolio.PrincipalPortfolio REBUILD;  

GO

ALTER INDEX IX_PrincipalPortfolio_ProActiveSlaId    ON Portfolio.PrincipalPortfolio REBUILD;  
GO

-- Enable all table constraints
ALTER TABLE Portfolio.PrincipalPortfolio CHECK CONSTRAINT ALL
GO

ALTER DATABASE SCD_2 SET RECOVERY FULL
GO 

