//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.Spooler
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobsSchedule
    {
        public long Id { get; set; }
        public bool Active { get; set; }
        public bool Daily { get; set; }
        public int DayOfWeek { get; set; }
        public System.DateTime ExactDate { get; set; }
        public string JobName { get; set; }
        public int MonthlyDayOfWeek { get; set; }
        public int MonthlyWeekNumber { get; set; }
        public string PathToJob { get; set; }
        public int TimeInHours { get; set; }
    }
}
