//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.CopyDataTool.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CountryGroup()
        {
            this.Country = new HashSet<Country>();
        }
    
        public long Id { get; set; }
        public bool AutoUploadInstallBase { get; set; }
        public string CountryDigit { get; set; }
        public string LUTCode { get; set; }
        public string Name { get; set; }
        public long RegionId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Country> Country { get; set; }
        public virtual Region Region { get; set; }
    }
}
