//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.CopyDataTool.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Country()
        {
            this.StandardWarrantyManualCost = new HashSet<StandardWarrantyManualCost>();
            this.LocalPortfolio = new HashSet<LocalPortfolio>();
        }
    
        public long Id { get; set; }
        public bool AssignedToMultiVendor { get; set; }
        public bool CanOverrideTransferCostAndPrice { get; set; }
        public bool CanStoreListAndDealerPrices { get; set; }
        public Nullable<long> ClusterRegionId { get; set; }
        public Nullable<long> CountryGroupId { get; set; }
        public long CurrencyId { get; set; }
        public string ISO3CountryCode { get; set; }
        public bool IsMaster { get; set; }
        public string Name { get; set; }
        public string QualityGateGroup { get; set; }
        public Nullable<long> RegionId { get; set; }
        public string SAPCountryCode { get; set; }
        public bool CanOverride2ndLevelSupportLocal { get; set; }
        public string InstallbaseGroup { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StandardWarrantyManualCost> StandardWarrantyManualCost { get; set; }
        public virtual ClusterRegion ClusterRegion { get; set; }
        public virtual CountryGroup CountryGroup { get; set; }
        public virtual Region Region { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocalPortfolio> LocalPortfolio { get; set; }
    }
}
