//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.CopyDataTool.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManualCost
    {
        public long PortfolioId { get; set; }
        public Nullable<double> DealerDiscount { get; set; }
        public Nullable<double> ListPrice { get; set; }
        public Nullable<double> ServiceTC { get; set; }
        public Nullable<double> ServiceTP { get; set; }
        public Nullable<double> DealerPrice { get; set; }
        public Nullable<long> ChangeUserId { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<double> ServiceTP1_Released { get; set; }
        public Nullable<double> ServiceTP2_Released { get; set; }
        public Nullable<double> ServiceTP3_Released { get; set; }
        public Nullable<double> ServiceTP4_Released { get; set; }
        public Nullable<double> ServiceTP5_Released { get; set; }
        public Nullable<double> ServiceTP1P_Released { get; set; }
        public Nullable<double> ServiceTP_Released { get; set; }
    
        public virtual LocalPortfolio LocalPortfolio { get; set; }
    }
}
