//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.CopyDataTool.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReactionTime_ReactionType_Avalability
    {
        public long Id { get; set; }
        public Nullable<long> AvailabilityId { get; set; }
        public Nullable<long> ReactionTimeId { get; set; }
        public Nullable<long> ReactionTypeId { get; set; }
        public bool IsDisabled { get; set; }
    
        public virtual Availability Availability { get; set; }
        public virtual ReactionTime ReactionTime { get; set; }
        public virtual ReactionType ReactionType { get; set; }
    }
}
