//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.CopyDataTool.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SCD_2SourceEntities : DbContext
    {
        public SCD_2SourceEntities()
            : base("name=SCD_2SourceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Availability> Availability { get; set; }
        public virtual DbSet<Duration> Duration { get; set; }
        public virtual DbSet<Duration_Availability> Duration_Availability { get; set; }
        public virtual DbSet<ProActiveSla> ProActiveSla { get; set; }
        public virtual DbSet<ReactionTime> ReactionTime { get; set; }
        public virtual DbSet<ReactionTime_Avalability> ReactionTime_Avalability { get; set; }
        public virtual DbSet<ReactionTime_ReactionType> ReactionTime_ReactionType { get; set; }
        public virtual DbSet<ReactionTime_ReactionType_Avalability> ReactionTime_ReactionType_Avalability { get; set; }
        public virtual DbSet<ReactionType> ReactionType { get; set; }
        public virtual DbSet<ServiceLocation> ServiceLocation { get; set; }
        public virtual DbSet<Year> Year { get; set; }
        public virtual DbSet<ManualCost> ManualCost { get; set; }
        public virtual DbSet<StandardWarrantyManualCost> StandardWarrantyManualCost { get; set; }
        public virtual DbSet<CentralContractGroup> CentralContractGroup { get; set; }
        public virtual DbSet<ClusterPla> ClusterPla { get; set; }
        public virtual DbSet<ClusterRegion> ClusterRegion { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<CountryGroup> CountryGroup { get; set; }
        public virtual DbSet<Pla> Pla { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<RoleCode> RoleCode { get; set; }
        public virtual DbSet<Sfab> Sfab { get; set; }
        public virtual DbSet<Sog> Sog { get; set; }
        public virtual DbSet<SwDigit> SwDigit { get; set; }
        public virtual DbSet<SwDigitLicense> SwDigitLicense { get; set; }
        public virtual DbSet<SwLicense> SwLicense { get; set; }
        public virtual DbSet<Wg> Wg { get; set; }
        public virtual DbSet<LocalPortfolio> LocalPortfolio { get; set; }
        public virtual DbSet<PrincipalPortfolio> PrincipalPortfolio { get; set; }
    }
}
