//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.CopyDataTool.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StandardWarrantyManualCost
    {
        public long Id { get; set; }
        public long CountryId { get; set; }
        public long WgId { get; set; }
        public long ChangeUserId { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public Nullable<double> StandardWarranty { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Wg Wg { get; set; }
    }
}
