//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.CopyDataTool.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Year
    {
        public long Id { get; set; }
        public bool IsProlongation { get; set; }
        public string Name { get; set; }
        public int Value { get; set; }
    
        public virtual Duration Duration { get; set; }
    }
}
