export const fakeHwCost = [
    {
        "id": "1",
        "country": "Russia",
        "wg": "WG0",
        "availability": "24x7",
        "duration": "3h",
        "reactionType": "recover",
        "reactionTime": "3h",
        "serviceLocation": "off side",
        "availabilityFee": 100.5,
        "credits": 8.3,
        "fieldServiceCost": 12.7,
        "hddRetention": 138.8,
        "localServiceStandardWarranty": 56.48,
        "logistic": 8.07,
        "materialOow": 99.88,
        "materialW": 99.87,
        "otherDirect": 34.45,
        "proActive": 0.3,
        "reinsurance": 2.5,
        "serviceSupport": 603.3,
        "serviceTC": 1600.00,
        "serviceTP": 0.00,
        "taxAndDutiesOow": 23.22,
        "taxAndDutiesW": 23.23,

        "CanOverrideTransferCostAndPrice": true
    },
    {
        "id": "2",
        "country": "Russia",
        "wg": "WG0",
        "availability": "24x7",
        "duration": "3h",
        "reactionType": "recover",
        "reactionTime": "3h",
        "serviceLocation": "off side",
        "availabilityFee": 100.5,
        "credits": 8.3,
        "fieldServiceCost": 12.7,
        "hddRetention": 138.8,
        "localServiceStandardWarranty": 56.48,
        "logistic": 8.07,
        "materialOow": 99.88,
        "materialW": 99.87,
        "otherDirect": 34.45,
        "proActive": 0.3,
        "reinsurance": 2.5,
        "serviceSupport": 603.3,
        "serviceTC": 1600.00,
        "serviceTP": 1705.04,
        "taxAndDutiesOow": 23.22,
        "taxAndDutiesW": 23.23
    },
    {
        "id": "3",
        "country": "Russia",
        "wg": "WG0",
        "availability": "24x7",
        "duration": "3h",
        "reactionType": "recover",
        "reactionTime": "3h",
        "serviceLocation": "off side",
        "availabilityFee": 100.5,
        "credits": 8.3,
        "fieldServiceCost": 12.7,
        "hddRetention": 138.8,
        "localServiceStandardWarranty": 56.48,
        "logistic": 8.07,
        "materialOow": 99.88,
        "materialW": 99.87,
        "otherDirect": 34.45,
        "proActive": 0.3,
        "reinsurance": 2.5,
        "serviceSupport": 603.3,
        "serviceTC": 1600.00,
        "serviceTP": 1705.04,
        "taxAndDutiesOow": 23.22,
        "taxAndDutiesW": 23.23
    },
    {
        "id": "4",
        "country": "Russia",
        "wg": "WG0",
        "availability": "24x7",
        "duration": "3h",
        "reactionType": "recover",
        "reactionTime": "3h",
        "serviceLocation": "off side",
        "availabilityFee": 100.5,
        "credits": 8.3,
        "fieldServiceCost": 12.7,
        "hddRetention": 138.8,
        "localServiceStandardWarranty": 56.48,
        "logistic": 8.07,
        "materialOow": 99.88,
        "materialW": 99.87,
        "otherDirect": 34.45,
        "proActive": 0.3,
        "reinsurance": 2.5,
        "serviceSupport": 603.3,
        "serviceTC": 1600.00,
        "serviceTP": 1705.04,
        "taxAndDutiesOow": 23.22,
        "taxAndDutiesW": 23.23
    },
    {
        "id": "5",
        "country": "Russia",
        "wg": "WG0",
        "availability": "24x7",
        "duration": "3h",
        "reactionType": "recover",
        "reactionTime": "3h",
        "serviceLocation": "off side",
        "availabilityFee": 100.5,
        "credits": 8.3,
        "fieldServiceCost": 12.7,
        "hddRetention": 138.8,
        "localServiceStandardWarranty": 56.48,
        "logistic": 8.07,
        "materialOow": 99.88,
        "materialW": 99.87,
        "otherDirect": 34.45,
        "proActive": 0.3,
        "reinsurance": 2.5,
        "serviceSupport": 603.3,
        "serviceTC": 1600.00,
        "serviceTP": 1705.04,
        "taxAndDutiesOow": 23.22,
        "taxAndDutiesW": 23.23
    },
    {
        "id": "6",
        "country": "Russia",
        "wg": "WG0",
        "availability": "24x7",
        "duration": "3h",
        "reactionType": "recover",
        "reactionTime": "3h",
        "serviceLocation": "off side",
        "availabilityFee": 100.5,
        "credits": 8.3,
        "fieldServiceCost": 12.7,
        "hddRetention": 138.8,
        "localServiceStandardWarranty": 56.48,
        "logistic": 8.07,
        "materialOow": 99.88,
        "materialW": 99.87,
        "otherDirect": 34.45,
        "proActive": 0.3,
        "reinsurance": 2.5,
        "serviceSupport": 603.3,
        "serviceTC": 1600.00,
        "serviceTP": 1705.04,
        "taxAndDutiesOow": 23.22,
        "taxAndDutiesW": 23.23
    },
    {
        "id": "7",
        "country": "Russia",
        "wg": "WG0",
        "availability": "24x7",
        "duration": "3h",
        "reactionType": "recover",
        "reactionTime": "3h",
        "serviceLocation": "off side",
        "availabilityFee": 100.5,
        "credits": 8.3,
        "fieldServiceCost": 12.7,
        "hddRetention": 138.8,
        "localServiceStandardWarranty": 56.48,
        "logistic": 8.07,
        "materialOow": 99.88,
        "materialW": 99.87,
        "otherDirect": 34.45,
        "proActive": 0.3,
        "reinsurance": 2.5,
        "serviceSupport": 603.3,
        "serviceTC": 1600.00,
        "serviceTP": 1705.04,
        "taxAndDutiesOow": 23.22,
        "taxAndDutiesW": 23.23
    },
    {
        "id": "8",
        "country": "Russia",
        "wg": "WG0",
        "availability": "24x7",
        "duration": "3h",
        "reactionType": "recover",
        "reactionTime": "3h",
        "serviceLocation": "off side",
        "availabilityFee": 100.5,
        "credits": 8.3,
        "fieldServiceCost": 12.7,
        "hddRetention": 138.8,
        "localServiceStandardWarranty": 56.48,
        "logistic": 8.07,
        "materialOow": 99.88,
        "materialW": 99.87,
        "otherDirect": 34.45,
        "proActive": 0.3,
        "reinsurance": 2.5,
        "serviceSupport": 603.3,
        "serviceTC": 1600.00,
        "serviceTP": 1705.04,
        "taxAndDutiesOow": 23.22,
        "taxAndDutiesW": 23.23
    },
    {
        "id": "9",
        "country": "Russia",
        "wg": "WG0",
        "availability": "24x7",
        "duration": "3h",
        "reactionType": "recover",
        "reactionTime": "3h",
        "serviceLocation": "off side",
        "availabilityFee": 100.5,
        "credits": 8.3,
        "fieldServiceCost": 12.7,
        "hddRetention": 138.8,
        "localServiceStandardWarranty": 56.48,
        "logistic": 8.07,
        "materialOow": 99.88,
        "materialW": 99.87,
        "otherDirect": 34.45,
        "proActive": 0.3,
        "reinsurance": 2.5,
        "serviceSupport": 603.3,
        "serviceTC": 1600.00,
        "serviceTP": 1705.04,
        "taxAndDutiesOow": 23.22,
        "taxAndDutiesW": 23.23
    },
    {
        "id": "10",
        "country": "Russia",
        "wg": "WG0",
        "availability": "24x7",
        "duration": "3h",
        "reactionType": "recover",
        "reactionTime": "3h",
        "serviceLocation": "off side",
        "availabilityFee": 100.5,
        "credits": 8.3,
        "fieldServiceCost": 12.7,
        "hddRetention": 138.8,
        "localServiceStandardWarranty": 56.48,
        "logistic": 8.07,
        "materialOow": 99.88,
        "materialW": 99.87,
        "otherDirect": 34.45,
        "proActive": 0.3,
        "reinsurance": 2.5,
        "serviceSupport": 603.3,
        "serviceTC": 1600.00,
        "serviceTP": 1705.04,
        "taxAndDutiesOow": 23.22,
        "taxAndDutiesW": 23.23
    }
]