export const fakeHwCost = [
    {
        "Id": "1",
        "Country": "Russia",
        "Wg": "WG0",
        "Availability": "24x7",
        "Duration": "3h",
        "ReactionType": "recover",
        "ReactionTime": "3h",
        "ServiceLocation": "off side",
        "AvailabilityFee": 100.5,
        "Credits": 8.3,
        "FieldServiceCost": 12.7,
        "HddRetention": 138.8,
        "LocalServiceStandardWarranty": 56.48,
        "Logistic": 8.07,
        "MaterialOow": 99.88,
        "MaterialW": 99.87,
        "OtherDirect": 34.45,
        "ProActive": 0.3,
        "Reinsurance": 2.5,
        "ServiceSupport": 603.3,
        "ServiceTC": 1600.00,
        "ServiceTP": 0.00,
        "TaxAndDutiesOow": 23.22,
        "TaxAndDutiesW": 23.23,

        "CanOverrideTransferCostAndPrice": true
    },
    {
        "Id": "2",
        "Country": "Russia",
        "Wg": "WG0",
        "Availability": "24x7",
        "Duration": "3h",
        "ReactionType": "recover",
        "ReactionTime": "3h",
        "ServiceLocation": "off side",
        "AvailabilityFee": 100.5,
        "Credits": 8.3,
        "FieldServiceCost": 12.7,
        "HddRetention": 138.8,
        "LocalServiceStandardWarranty": 56.48,
        "Logistic": 8.07,
        "MaterialOow": 99.88,
        "MaterialW": 99.87,
        "OtherDirect": 34.45,
        "ProActive": 0.3,
        "Reinsurance": 2.5,
        "ServiceSupport": 603.3,
        "ServiceTC": 1600.00,
        "ServiceTP": 1705.04,
        "TaxAndDutiesOow": 23.22,
        "TaxAndDutiesW": 23.23
    },
    {
        "Id": "3",
        "Country": "Russia",
        "Wg": "WG0",
        "Availability": "24x7",
        "Duration": "3h",
        "ReactionType": "recover",
        "ReactionTime": "3h",
        "ServiceLocation": "off side",
        "AvailabilityFee": 100.5,
        "Credits": 8.3,
        "FieldServiceCost": 12.7,
        "HddRetention": 138.8,
        "LocalServiceStandardWarranty": 56.48,
        "Logistic": 8.07,
        "MaterialOow": 99.88,
        "MaterialW": 99.87,
        "OtherDirect": 34.45,
        "ProActive": 0.3,
        "Reinsurance": 2.5,
        "ServiceSupport": 603.3,
        "ServiceTC": 1600.00,
        "ServiceTP": 1705.04,
        "TaxAndDutiesOow": 23.22,
        "TaxAndDutiesW": 23.23
    },
    {
        "Id": "4",
        "Country": "Russia",
        "Wg": "WG0",
        "Availability": "24x7",
        "Duration": "3h",
        "ReactionType": "recover",
        "ReactionTime": "3h",
        "ServiceLocation": "off side",
        "AvailabilityFee": 100.5,
        "Credits": 8.3,
        "FieldServiceCost": 12.7,
        "HddRetention": 138.8,
        "LocalServiceStandardWarranty": 56.48,
        "Logistic": 8.07,
        "MaterialOow": 99.88,
        "MaterialW": 99.87,
        "OtherDirect": 34.45,
        "ProActive": 0.3,
        "Reinsurance": 2.5,
        "ServiceSupport": 603.3,
        "ServiceTC": 1600.00,
        "ServiceTP": 1705.04,
        "TaxAndDutiesOow": 23.22,
        "TaxAndDutiesW": 23.23
    },
    {
        "Id": "5",
        "Country": "Russia",
        "Wg": "WG0",
        "Availability": "24x7",
        "Duration": "3h",
        "ReactionType": "recover",
        "ReactionTime": "3h",
        "ServiceLocation": "off side",
        "AvailabilityFee": 100.5,
        "Credits": 8.3,
        "FieldServiceCost": 12.7,
        "HddRetention": 138.8,
        "LocalServiceStandardWarranty": 56.48,
        "Logistic": 8.07,
        "MaterialOow": 99.88,
        "MaterialW": 99.87,
        "OtherDirect": 34.45,
        "ProActive": 0.3,
        "Reinsurance": 2.5,
        "ServiceSupport": 603.3,
        "ServiceTC": 1600.00,
        "ServiceTP": 1705.04,
        "TaxAndDutiesOow": 23.22,
        "TaxAndDutiesW": 23.23
    },
    {
        "Id": "6",
        "Country": "Russia",
        "Wg": "WG0",
        "Availability": "24x7",
        "Duration": "3h",
        "ReactionType": "recover",
        "ReactionTime": "3h",
        "ServiceLocation": "off side",
        "AvailabilityFee": 100.5,
        "Credits": 8.3,
        "FieldServiceCost": 12.7,
        "HddRetention": 138.8,
        "LocalServiceStandardWarranty": 56.48,
        "Logistic": 8.07,
        "MaterialOow": 99.88,
        "MaterialW": 99.87,
        "OtherDirect": 34.45,
        "ProActive": 0.3,
        "Reinsurance": 2.5,
        "ServiceSupport": 603.3,
        "ServiceTC": 1600.00,
        "ServiceTP": 1705.04,
        "TaxAndDutiesOow": 23.22,
        "TaxAndDutiesW": 23.23
    },
    {
        "Id": "7",
        "Country": "Russia",
        "Wg": "WG0",
        "Availability": "24x7",
        "Duration": "3h",
        "ReactionType": "recover",
        "ReactionTime": "3h",
        "ServiceLocation": "off side",
        "AvailabilityFee": 100.5,
        "Credits": 8.3,
        "FieldServiceCost": 12.7,
        "HddRetention": 138.8,
        "LocalServiceStandardWarranty": 56.48,
        "Logistic": 8.07,
        "MaterialOow": 99.88,
        "MaterialW": 99.87,
        "OtherDirect": 34.45,
        "ProActive": 0.3,
        "Reinsurance": 2.5,
        "ServiceSupport": 603.3,
        "ServiceTC": 1600.00,
        "ServiceTP": 1705.04,
        "TaxAndDutiesOow": 23.22,
        "TaxAndDutiesW": 23.23
    },
    {
        "Id": "8",
        "Country": "Russia",
        "Wg": "WG0",
        "Availability": "24x7",
        "Duration": "3h",
        "ReactionType": "recover",
        "ReactionTime": "3h",
        "ServiceLocation": "off side",
        "AvailabilityFee": 100.5,
        "Credits": 8.3,
        "FieldServiceCost": 12.7,
        "HddRetention": 138.8,
        "LocalServiceStandardWarranty": 56.48,
        "Logistic": 8.07,
        "MaterialOow": 99.88,
        "MaterialW": 99.87,
        "OtherDirect": 34.45,
        "ProActive": 0.3,
        "Reinsurance": 2.5,
        "ServiceSupport": 603.3,
        "ServiceTC": 1600.00,
        "ServiceTP": 1705.04,
        "TaxAndDutiesOow": 23.22,
        "TaxAndDutiesW": 23.23
    },
    {
        "Id": "9",
        "Country": "Russia",
        "Wg": "WG0",
        "Availability": "24x7",
        "Duration": "3h",
        "ReactionType": "recover",
        "ReactionTime": "3h",
        "ServiceLocation": "off side",
        "AvailabilityFee": 100.5,
        "Credits": 8.3,
        "FieldServiceCost": 12.7,
        "HddRetention": 138.8,
        "LocalServiceStandardWarranty": 56.48,
        "Logistic": 8.07,
        "MaterialOow": 99.88,
        "MaterialW": 99.87,
        "OtherDirect": 34.45,
        "ProActive": 0.3,
        "Reinsurance": 2.5,
        "ServiceSupport": 603.3,
        "ServiceTC": 1600.00,
        "ServiceTP": 1705.04,
        "TaxAndDutiesOow": 23.22,
        "TaxAndDutiesW": 23.23
    },
    {
        "Id": "10",
        "Country": "Russia",
        "Wg": "WG0",
        "Availability": "24x7",
        "Duration": "3h",
        "ReactionType": "recover",
        "ReactionTime": "3h",
        "ServiceLocation": "off side",
        "AvailabilityFee": 100.5,
        "Credits": 8.3,
        "FieldServiceCost": 12.7,
        "HddRetention": 138.8,
        "LocalServiceStandardWarranty": 56.48,
        "Logistic": 8.07,
        "MaterialOow": 99.88,
        "MaterialW": 99.87,
        "OtherDirect": 34.45,
        "ProActive": 0.3,
        "Reinsurance": 2.5,
        "ServiceSupport": 603.3,
        "ServiceTC": 1600.00,
        "ServiceTP": 1705.04,
        "TaxAndDutiesOow": 23.22,
        "TaxAndDutiesW": 23.23
    }
]