//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.DataAccessLayer.External.Por
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FrieseEntities : DbContext
    {
        public FrieseEntities()
            : base("name=FrieseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Intranet_SOG_Info> Intranet_SOG_Info { get; set; }
        public virtual DbSet<Intranet_WG_Info> Intranet_WG_Info { get; set; }
        public virtual DbSet<v_SAR_new_codes> v_SAR_new_codes { get; set; }
    }
}
