//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.DataAccessLayer.External.Por
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intranet_WG_Info
    {
        public string WG { get; set; }
        public string WG_Definition { get; set; }
        public string Activ { get; set; }
        public string PLA { get; set; }
        public string Service_Types { get; set; }
        public string Only_Contracts_allowed { get; set; }
        public string max_Spares_availability { get; set; }
        public string Portfolio_Alignment_Category { get; set; }
        public string Reinsurance_Process_Info { get; set; }
        public string Recommended_Category { get; set; }
        public string SCD_relevant { get; set; }
        public string EOL_Date { get; set; }
        public string Global_Scope { get; set; }
        public string Global_Support_Pack { get; set; }
        public string SWAP { get; set; }
        public string HW_Produktbeschreibung { get; set; }
        public string Harm_STDW_Duration { get; set; }
        public string SOG { get; set; }
        public string SOG_Definition { get; set; }
        public string ServiceFabgr { get; set; }
    }
}
