//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.DataAccessLayer.External.Por
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCD2_WarrantyGroups
    {
        public string Warranty_Group { get; set; }
        public string Warranty_Group_Name { get; set; }
        public string Warranty_PLA { get; set; }
        public string Active_Flag { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public string Service_Type { get; set; }
        public string CRU { get; set; }
        public string FabGrp { get; set; }
        public string Spares_availability { get; set; }
        public string Alignment { get; set; }
        public string Warranty_Calculation_relevant { get; set; }
        public string EOL { get; set; }
        public string Service_Types { get; set; }
        public string SOG { get; set; }
        public string SCD_ServiceType { get; set; }
    }
}
