// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Gdc.Scd.Import.Por.Core.Scripts
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dev\SCD\Gdc.Scd.Import.Por.Core\Scripts\UpdateProactive.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class UpdateProactive : BaseUpdateCost
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\ndeclare @wg dbo.ListID;\r\ninsert into @wg(id) select id from InputAtoms.Wg where" +
                    " Deactivated = 0 and UPPER(name) in (");
            
            #line 4 "C:\Dev\SCD\Gdc.Scd.Import.Por.Core\Scripts\UpdateProactive.tt"
 PrintNames(); 
            
            #line default
            #line hidden
            this.Write(@")

IF OBJECT_ID('tempdb..#tmp') IS NOT NULL DROP TABLE #tmp;
IF OBJECT_ID('tempdb..#tmpMin') IS NOT NULL DROP TABLE #tmpMin;

select c.* into #tmp
from Hardware.MarkupStandardWaranty c
where c.Deactivated = 0 and not exists(select * from @wg where Id = c.Wg)

create index ix_tmp_Country_SLA on #tmp(Country, ");
            
            #line 13 "C:\Dev\SCD\Gdc.Scd.Import.Por.Core\Scripts\UpdateProactive.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.field));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\nselect    t.Country\r\n        , t.");
            
            #line 16 "C:\Dev\SCD\Gdc.Scd.Import.Por.Core\Scripts\UpdateProactive.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.field));
            
            #line default
            #line hidden
            this.Write(@"

        , case when min(MarkupFactorStandardWarranty) = max(MarkupFactorStandardWarranty) then min(MarkupFactorStandardWarranty) else null end as MarkupFactorStandardWarranty
        , case when min(MarkupFactorStandardWarranty_Approved) = max(MarkupFactorStandardWarranty_Approved) then min(MarkupFactorStandardWarranty_Approved) else null end as MarkupFactorStandardWarranty_Approved
        , case when min(MarkupStandardWarranty) = max(MarkupStandardWarranty) then min(MarkupStandardWarranty) else null end as MarkupStandardWarranty
        , case when min(MarkupStandardWarranty_Approved) = max(MarkupStandardWarranty_Approved) then min(MarkupStandardWarranty_Approved) else null end as MarkupStandardWarranty_Approved

into #tmpMin
from #tmp t
group by t.Country, t.");
            
            #line 25 "C:\Dev\SCD\Gdc.Scd.Import.Por.Core\Scripts\UpdateProactive.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.field));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\ncreate index ix_tmpmin_Country_SLA on #tmp(Country, ");
            
            #line 27 "C:\Dev\SCD\Gdc.Scd.Import.Por.Core\Scripts\UpdateProactive.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.field));
            
            #line default
            #line hidden
            this.Write(@");

update c set
      MarkupFactorStandardWarranty = coalesce(t.MarkupFactorStandardWarranty, c.MarkupFactorStandardWarranty)
    , MarkupFactorStandardWarranty_Approved = coalesce(t.MarkupFactorStandardWarranty_Approved, c.MarkupFactorStandardWarranty_Approved)
    , MarkupStandardWarranty = coalesce(t.MarkupStandardWarranty, c.MarkupStandardWarranty)
    , MarkupStandardWarranty_Approved = coalesce(t.MarkupStandardWarranty_Approved, c.MarkupStandardWarranty_Approved)

from Hardware.MarkupStandardWaranty c
inner join #tmpMin t on t.Country = c.Country and t.");
            
            #line 36 "C:\Dev\SCD\Gdc.Scd.Import.Por.Core\Scripts\UpdateProactive.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.field));
            
            #line default
            #line hidden
            this.Write(" = c.");
            
            #line 36 "C:\Dev\SCD\Gdc.Scd.Import.Por.Core\Scripts\UpdateProactive.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.field));
            
            #line default
            #line hidden
            this.Write(" \r\nwhere c.Deactivated = 0 and exists(select * from @wg where Id = c.Wg);\r\n\r\nIF O" +
                    "BJECT_ID(\'tempdb..#tmp\') IS NOT NULL DROP TABLE #tmp\r\nIF OBJECT_ID(\'tempdb..#tmp" +
                    "Min\') IS NOT NULL DROP TABLE #tmpMin;\r\n\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
