// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Gdc.Scd.Import.Por.Core.Scripts
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dev\SCD\Gdc.Scd.Import.Por.Core\Scripts\UpdateCost.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class UpdateCost : UpdateCostBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\ndeclare @wg dbo.ListID;\r\ninsert into @wg(id) select id from InputAtoms.Wg where" +
                    " Deactivated = 0 and UPPER(name) in (");
            
            #line 4 "C:\Dev\SCD\Gdc.Scd.Import.Por.Core\Scripts\UpdateCost.tt"
 WriteNames(); 
            
            #line default
            #line hidden
            this.Write(")\r\n\r\nIF OBJECT_ID(\'tempdb..#tmp\') IS NOT NULL DROP TABLE #tmp;\r\nIF OBJECT_ID(\'tem" +
                    "pdb..#tmpMin\') IS NOT NULL DROP TABLE #tmpMin;\r\n\r\nselect c.* into #tmp\r\nfrom ");
            
            #line 10 "C:\Dev\SCD\Gdc.Scd.Import.Por.Core\Scripts\UpdateCost.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table));
            
            #line default
            #line hidden
            this.Write(" c\r\nwhere c.Deactivated = 0 and not exists(select * from @wg where Id = c.Wg);\r\n\r" +
                    "\ncreate index ix_tmp_Country_SLA on #tmp(");
            
            #line 13 "C:\Dev\SCD\Gdc.Scd.Import.Por.Core\Scripts\UpdateCost.tt"
 WriteDeps(); 
            
            #line default
            #line hidden
            this.Write(");\r\n\r\nselect    ");
            
            #line 15 "C:\Dev\SCD\Gdc.Scd.Import.Por.Core\Scripts\UpdateCost.tt"
 WriteDeps(); 
            
            #line default
            #line hidden
            this.Write("\r\n        , case when min(StandardHandling) = max(StandardHandling) then min(Stan" +
                    "dardHandling) else null end as StandardHandling\r\n        , case when min(HighAva" +
                    "ilabilityHandling) = max(HighAvailabilityHandling) then min(HighAvailabilityHand" +
                    "ling) else null end as HighAvailabilityHandling\r\n        , case when min(Standar" +
                    "dDelivery) = max(StandardDelivery) then min(StandardDelivery) else null end as S" +
                    "tandardDelivery\r\n        , case when min(ExpressDelivery) = max(ExpressDelivery)" +
                    " then min(ExpressDelivery) else null end as ExpressDelivery\r\n        , case when" +
                    " min(TaxiCourierDelivery) = max(TaxiCourierDelivery) then min(TaxiCourierDeliver" +
                    "y) else null end as TaxiCourierDelivery\r\n        , case when min(ReturnDeliveryF" +
                    "actory) = max(ReturnDeliveryFactory) then min(ReturnDeliveryFactory) else null e" +
                    "nd as ReturnDeliveryFactory\r\n\r\n        , case when min(StandardHandling_Approved" +
                    ") = max(StandardHandling_Approved) then min(StandardHandling_Approved) else null" +
                    " end as StandardHandling_Approved\r\n        , case when min(HighAvailabilityHandl" +
                    "ing_Approved) = max(HighAvailabilityHandling_Approved) then min(HighAvailability" +
                    "Handling_Approved) else null end as HighAvailabilityHandling_Approved\r\n        ," +
                    " case when min(StandardDelivery_Approved) = max(StandardDelivery_Approved) then " +
                    "min(StandardDelivery_Approved) else null end as StandardDelivery_Approved\r\n     " +
                    "   , case when min(ExpressDelivery_Approved) = max(ExpressDelivery_Approved) the" +
                    "n min(ExpressDelivery_Approved) else null end as ExpressDelivery_Approved\r\n     " +
                    "   , case when min(TaxiCourierDelivery_Approved) = max(TaxiCourierDelivery_Appro" +
                    "ved) then min(TaxiCourierDelivery_Approved) else null end as TaxiCourierDelivery" +
                    "_Approved\r\n        , case when min(ReturnDeliveryFactory_Approved) = max(ReturnD" +
                    "eliveryFactory_Approved) then min(ReturnDeliveryFactory_Approved) else null end " +
                    "as ReturnDeliveryFactory_Approved\r\n\r\ninto #tmpMin\r\nfrom #tmp \r\ngroup by ");
            
            #line 33 "C:\Dev\SCD\Gdc.Scd.Import.Por.Core\Scripts\UpdateCost.tt"
 WriteDeps(); 
            
            #line default
            #line hidden
            this.Write("\r\ncreate index ix_tmpmin_Country_SLA on #tmpMin(");
            
            #line 35 "C:\Dev\SCD\Gdc.Scd.Import.Por.Core\Scripts\UpdateCost.tt"
 WriteDeps(); 
            
            #line default
            #line hidden
            this.Write(@");

update c set
      StandardHandling = coalesce(t.StandardHandling, c.StandardHandling) 
    , HighAvailabilityHandling = coalesce(t.HighAvailabilityHandling, c.HighAvailabilityHandling) 
    , StandardDelivery = coalesce(t.StandardDelivery, c.StandardDelivery) 
    , ExpressDelivery = coalesce(t.ExpressDelivery, c.ExpressDelivery) 
    , TaxiCourierDelivery = coalesce(t.TaxiCourierDelivery, c.TaxiCourierDelivery) 
    , ReturnDeliveryFactory = coalesce(t.ReturnDeliveryFactory, c.ReturnDeliveryFactory) 

    , StandardHandling_Approved = coalesce(t.StandardHandling_Approved, c.StandardHandling_Approved) 
    , HighAvailabilityHandling_Approved = coalesce(t.HighAvailabilityHandling_Approved, c.HighAvailabilityHandling_Approved) 
    , StandardDelivery_Approved = coalesce(t.StandardDelivery_Approved, c.StandardDelivery_Approved) 
    , ExpressDelivery_Approved = coalesce(t.ExpressDelivery_Approved, c.ExpressDelivery_Approved) 
    , TaxiCourierDelivery_Approved = coalesce(t.TaxiCourierDelivery_Approved, c.TaxiCourierDelivery_Approved) 
    , ReturnDeliveryFactory_Approved = coalesce(t.ReturnDeliveryFactory_Approved, c.ReturnDeliveryFactory_Approved) 

from ");
            
            #line 52 "C:\Dev\SCD\Gdc.Scd.Import.Por.Core\Scripts\UpdateCost.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table));
            
            #line default
            #line hidden
            this.Write(" c\r\ninner join #tmpMin t on ");
            
            #line 53 "C:\Dev\SCD\Gdc.Scd.Import.Por.Core\Scripts\UpdateCost.tt"
 WriteJoinByDeps(); 
            
            #line default
            #line hidden
            this.Write(" \r\nwhere c.Deactivated = 0 and exists(select * from @wg where Id = c.Wg);\r\n\r\nIF O" +
                    "BJECT_ID(\'tempdb..#tmp\') IS NOT NULL DROP TABLE #tmp\r\nIF OBJECT_ID(\'tempdb..#tmp" +
                    "Min\') IS NOT NULL DROP TABLE #tmpMin;\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class UpdateCostBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
