export const fakeDenied = [
    {
        "id": "1",
        "country": "Russia",
        "WG": "WG0",
        "availability": "24x7",
        "duration": "3h",
        "reactType": "recover",
        "reactionTime": "3h",
        "serviceLocation": "off side",
        "isGlobalPortfolio": true,
        "isMasterPortfolio": false,
        "isCorePortfolio": true
    },
    {
        "id": "2",
        "country": "Russia",
        "WG": "WG0",
        "availability": "24x7",
        "duration": "3h",
        "reactType": "recover",
        "reactionTime": "3h",
        "serviceLocation": "off side",
        "isGlobalPortfolio": true,
        "isMasterPortfolio": false,
        "isCorePortfolio": true
    },
    {
        "id": "3",
        "country": "Russia",
        "WG": "WG0",
        "availability": "24x7",
        "duration": "3h",
        "reactType": "recover",
        "reactionTime": "3h",
        "serviceLocation": "off side",
        "isGlobalPortfolio": true,
        "isMasterPortfolio": false,
        "isCorePortfolio": true
    },
    {
        "id": "4",
        "country": "Russia",
        "WG": "WG0",
        "availability": "24x7",
        "duration": "3h",
        "reactType": "recover",
        "reactionTime": "3h",
        "serviceLocation": "off side",
        "isGlobalPortfolio": true,
        "isMasterPortfolio": false,
        "isCorePortfolio": true
    },
    {
        "id": "5",
        "country": "Russia",
        "WG": "WG0",
        "availability": "24x7",
        "duration": "3h",
        "reactType": "recover",
        "reactionTime": "3h",
        "serviceLocation": "off side",
        "isGlobalPortfolio": true,
        "isMasterPortfolio": false,
        "isCorePortfolio": true
    },
    {
        "id": "6",
        "country": "Russia",
        "WG": "WG0",
        "availability": "24x7",
        "duration": "3h",
        "reactType": "recover",
        "reactionTime": "3h",
        "serviceLocation": "off side",
        "isGlobalPortfolio": true,
        "isMasterPortfolio": false,
        "isCorePortfolio": true
    },
    {
        "id": "7",
        "country": "Russia",
        "WG": "WG0",
        "availability": "24x7",
        "duration": "3h",
        "reactType": "recover",
        "reactionTime": "3h",
        "serviceLocation": "off side",
        "isGlobalPortfolio": true,
        "isMasterPortfolio": false,
        "isCorePortfolio": true
    },
    {
        "id": "8",
        "country": "Russia",
        "WG": "WG0",
        "availability": "24x7",
        "duration": "3h",
        "reactType": "recover",
        "reactionTime": "3h",
        "serviceLocation": "off side",
        "isGlobalPortfolio": true,
        "isMasterPortfolio": false,
        "isCorePortfolio": true
    },
    {
        "id": "9",
        "country": "Russia",
        "WG": "WG0",
        "availability": "24x7",
        "duration": "3h",
        "reactType": "recover",
        "reactionTime": "3h",
        "serviceLocation": "off side",
        "isGlobalPortfolio": true,
        "isMasterPortfolio": false,
        "isCorePortfolio": true
    },
    {
        "id": "10",
        "country": "Russia",
        "WG": "WG0",
        "availability": "24x7",
        "duration": "3h",
        "reactType": "recover",
        "reactionTime": "3h",
        "serviceLocation": "off side",
        "isGlobalPortfolio": true,
        "isMasterPortfolio": false,
        "isCorePortfolio": true
    }
]