//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.Tests.Integration.BusinessLogicLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AfrYear
    {
        public long Wg { get; set; }
        public Nullable<double> AFR1 { get; set; }
        public Nullable<double> AFR2 { get; set; }
        public Nullable<double> AFR3 { get; set; }
        public Nullable<double> AFR4 { get; set; }
        public Nullable<double> AFR5 { get; set; }
        public Nullable<double> AFRP1 { get; set; }
        public Nullable<double> AFR1_Approved { get; set; }
        public Nullable<double> AFR2_Approved { get; set; }
        public Nullable<double> AFR3_Approved { get; set; }
        public Nullable<double> AFR4_Approved { get; set; }
        public Nullable<double> AFR5_Approved { get; set; }
        public Nullable<double> AFRP1_Approved { get; set; }
    
        public virtual Wg Wg1 { get; set; }
    }
}
