//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.Tests.Integration.BusinessLogicLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvailabilityFee
    {
        public long Id { get; set; }
        public long CountryId { get; set; }
        public long ReactionTimeId { get; set; }
        public long ReactionTypeId { get; set; }
        public long ServiceLocationId { get; set; }
    
        public virtual Country1 Country1 { get; set; }
        public virtual ReactionTime ReactionTime { get; set; }
        public virtual ReactionType ReactionType { get; set; }
        public virtual ServiceLocation ServiceLocation { get; set; }
    }
}
