//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.Tests.Integration.BusinessLogicLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvailabilityFee
    {
        public long Id { get; set; }
        public Nullable<double> AverageContractDuration { get; set; }
        public Nullable<double> AverageContractDuration_Approved { get; set; }
        public Nullable<double> CostPerKit { get; set; }
        public Nullable<double> CostPerKitJapanBuy { get; set; }
        public Nullable<double> CostPerKitJapanBuy_Approved { get; set; }
        public Nullable<double> CostPerKit_Approved { get; set; }
        public Nullable<long> Country { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<System.DateTime> DeactivatedDateTime { get; set; }
        public Nullable<double> InstalledBaseHighAvailability { get; set; }
        public Nullable<double> InstalledBaseHighAvailability_Approved { get; set; }
        public Nullable<bool> JapanBuy { get; set; }
        public Nullable<bool> JapanBuy_Approved { get; set; }
        public Nullable<double> MaxQty { get; set; }
        public Nullable<double> MaxQty_Approved { get; set; }
        public System.DateTime ModifiedDateTime { get; set; }
        public Nullable<double> StockValueFj { get; set; }
        public Nullable<double> StockValueFj_Approved { get; set; }
        public Nullable<double> StockValueMv { get; set; }
        public Nullable<double> StockValueMv_Approved { get; set; }
        public Nullable<double> TotalLogisticsInfrastructureCost { get; set; }
        public Nullable<double> TotalLogisticsInfrastructureCost_Approved { get; set; }
        public Nullable<long> Wg { get; set; }
    
        public virtual Country Country1 { get; set; }
        public virtual Wg Wg1 { get; set; }
    }
}
