//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.Tests.Integration.BusinessLogicLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvailabilityFeeCalcView
    {
        public Nullable<long> Country { get; set; }
        public Nullable<long> Wg { get; set; }
        public int IsMultiVendor { get; set; }
        public Nullable<double> IB { get; set; }
        public Nullable<double> IB_Approved { get; set; }
        public Nullable<double> TotalLogisticsInfrastructureCost { get; set; }
        public Nullable<double> TotalLogisticsInfrastructureCost_Approved { get; set; }
        public Nullable<double> StockValue { get; set; }
        public Nullable<double> StockValue_Approved { get; set; }
        public Nullable<double> AverageContractDuration { get; set; }
        public Nullable<double> AverageContractDuration_Approved { get; set; }
        public Nullable<double> CostPerKit { get; set; }
        public Nullable<double> CostPerKit_Approved { get; set; }
        public Nullable<double> MaxQty { get; set; }
        public Nullable<double> MaxQty_Approved { get; set; }
        public Nullable<double> Total_IB { get; set; }
        public Nullable<double> Total_IB_Approved { get; set; }
        public Nullable<double> Total_IB_VENDOR { get; set; }
        public Nullable<double> Total_IB_VENDOR_Approved { get; set; }
        public Nullable<double> Total_KC_MQ_IB_VENDOR { get; set; }
        public Nullable<double> Total_KC_MQ_IB_VENDOR_Approved { get; set; }
        public Nullable<double> YI { get; set; }
        public Nullable<double> YI_Approved { get; set; }
        public Nullable<double> TISC { get; set; }
        public Nullable<double> TISC_Approved { get; set; }
        public Nullable<double> Fee { get; set; }
        public Nullable<double> Fee_Approved { get; set; }
    }
}
