//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.Tests.Integration.BusinessLogicLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Availability1
    {
        public long CostBlockHistory { get; set; }
        public Nullable<long> Availability { get; set; }
    
        public virtual Availability Availability2 { get; set; }
        public virtual CostBlockHistory CostBlockHistory1 { get; set; }
    }
}
