//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.Tests.Integration.BusinessLogicLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CdCsConfiguration
    {
        public long Id { get; set; }
        public long CountryId { get; set; }
        public string FileFolderUrl { get; set; }
        public string FileWebUrl { get; set; }
    
        public virtual Country1 Country1 { get; set; }
    }
}
