//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.Tests.Integration.BusinessLogicLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuration
    {
        public long Id { get; set; }
        public string Culture { get; set; }
        public string Delimeter { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public bool HasHeader { get; set; }
        public int ImportMode { get; set; }
        public string Name { get; set; }
        public int Occurancy { get; set; }
        public Nullable<System.DateTime> ProcessedDateTime { get; set; }
        public string ProcessedFilesPath { get; set; }
    }
}
