//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.Tests.Integration.BusinessLogicLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryView
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string ISO3CountryCode { get; set; }
        public bool IsMaster { get; set; }
        public string SAPCountryCode { get; set; }
        public Nullable<long> CountryGroupId { get; set; }
        public string CountryGroup { get; set; }
        public string LUTCode { get; set; }
        public Nullable<long> ClusterRegionId { get; set; }
        public string ClusterRegion { get; set; }
        public Nullable<long> RegionId { get; set; }
        public string Region { get; set; }
        public Nullable<long> CurrencyId { get; set; }
        public string Currency { get; set; }
    }
}
