//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.Tests.Integration.BusinessLogicLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldServiceCost
    {
        public long Id { get; set; }
        public long Country { get; set; }
        public long Pla { get; set; }
        public long CentralContractGroup { get; set; }
        public long Wg { get; set; }
        public long ServiceLocation { get; set; }
        public long ReactionTimeType { get; set; }
        public Nullable<double> RepairTime { get; set; }
        public Nullable<double> TravelTime { get; set; }
        public Nullable<double> LabourCost { get; set; }
        public Nullable<double> TravelCost { get; set; }
        public Nullable<double> PerformanceRate { get; set; }
        public Nullable<double> TimeAndMaterialShare { get; set; }
        public Nullable<double> RepairTime_Approved { get; set; }
        public Nullable<double> TravelTime_Approved { get; set; }
        public Nullable<double> LabourCost_Approved { get; set; }
        public Nullable<double> TravelCost_Approved { get; set; }
        public Nullable<double> PerformanceRate_Approved { get; set; }
        public Nullable<double> TimeAndMaterialShare_Approved { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<System.DateTime> DeactivatedDateTime { get; set; }
    
        public virtual ReactionTime_ReactionType ReactionTime_ReactionType { get; set; }
        public virtual ServiceLocation ServiceLocation1 { get; set; }
        public virtual CentralContractGroup1 CentralContractGroup1 { get; set; }
        public virtual Country1 Country1 { get; set; }
        public virtual Pla1 Pla1 { get; set; }
        public virtual Wg1 Wg1 { get; set; }
    }
}
