//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.Tests.Integration.BusinessLogicLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldServiceCostView
    {
        public long Country { get; set; }
        public long Wg { get; set; }
        public int IsMultiVendor { get; set; }
        public Nullable<double> OnsiteHourlyRates { get; set; }
        public Nullable<double> OnsiteHourlyRates_Approved { get; set; }
        public long ServiceLocation { get; set; }
        public Nullable<long> ReactionTypeId { get; set; }
        public Nullable<long> ReactionTimeId { get; set; }
        public Nullable<double> RepairTime { get; set; }
        public Nullable<double> RepairTime_Approved { get; set; }
        public Nullable<double> TravelTime { get; set; }
        public Nullable<double> TravelTime_Approved { get; set; }
        public Nullable<double> LabourCost { get; set; }
        public Nullable<double> LabourCost_Approved { get; set; }
        public Nullable<double> TravelCost { get; set; }
        public Nullable<double> TravelCost_Approved { get; set; }
        public Nullable<double> PerformanceRate { get; set; }
        public Nullable<double> PerformanceRate_Approved { get; set; }
        public Nullable<double> TimeAndMaterialShare { get; set; }
        public Nullable<double> TimeAndMaterialShare_Approved { get; set; }
    }
}
