//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.Tests.Integration.BusinessLogicLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hardware_ServiceSupportCost
    {
        public long Id { get; set; }
        public Nullable<long> Country { get; set; }
        public Nullable<long> ClusterPla { get; set; }
        public Nullable<long> ClusterRegion { get; set; }
        public Nullable<double> C1stLevelSupportCostsCountry { get; set; }
        public Nullable<double> C2ndLevelSupportCostsClusterRegion { get; set; }
        public Nullable<double> C2ndLevelSupportCostsLocal { get; set; }
        public long CostBlockHistory { get; set; }
    
        public virtual CostBlockHistory CostBlockHistory1 { get; set; }
        public virtual ClusterPla1 ClusterPla1 { get; set; }
        public virtual ClusterRegion1 ClusterRegion1 { get; set; }
        public virtual Country1 Country1 { get; set; }
    }
}
