//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.Tests.Integration.BusinessLogicLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HddRetByDurationView
    {
        public long WgID { get; set; }
        public long DurID { get; set; }
        public Nullable<double> HddRet { get; set; }
        public Nullable<double> HddRet_Approved { get; set; }
    }
}
