//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.Tests.Integration.BusinessLogicLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HddRetention
    {
        public long Id { get; set; }
        public long Wg { get; set; }
        public long Year { get; set; }
        public Nullable<double> HddFr { get; set; }
        public Nullable<double> HddMaterialCost { get; set; }
        public Nullable<double> HddFr_Approved { get; set; }
        public Nullable<double> HddMaterialCost_Approved { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<System.DateTime> DeactivatedDateTime { get; set; }
        public Nullable<double> HddRet { get; set; }
        public Nullable<double> HddRet_Approved { get; set; }
    
        public virtual Year Year1 { get; set; }
        public virtual Wg1 Wg1 { get; set; }
    }
}
