//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.Tests.Integration.BusinessLogicLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HwFspCodeTranslation
    {
        public long Id { get; set; }
        public Nullable<long> AvailabilityId { get; set; }
        public Nullable<long> CountryId { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<long> DurationId { get; set; }
        public string EKKey { get; set; }
        public string EKSAPKey { get; set; }
        public Nullable<bool> IsStandardWarranty { get; set; }
        public string Name { get; set; }
        public Nullable<long> ProactiveSlaId { get; set; }
        public Nullable<long> ReactionTimeId { get; set; }
        public Nullable<long> ReactionTypeId { get; set; }
        public string SCD_ServiceType { get; set; }
        public string SecondSLA { get; set; }
        public string ServiceDescription { get; set; }
        public Nullable<long> ServiceLocationId { get; set; }
        public string ServiceType { get; set; }
        public string Status { get; set; }
        public long WgId { get; set; }
        public Nullable<int> SlaHash { get; set; }
    
        public virtual Availability Availability { get; set; }
        public virtual Duration Duration { get; set; }
        public virtual ProActiveSla ProActiveSla { get; set; }
        public virtual ReactionTime ReactionTime { get; set; }
        public virtual ReactionType ReactionType { get; set; }
        public virtual ServiceLocation ServiceLocation { get; set; }
        public virtual Country1 Country1 { get; set; }
        public virtual Wg1 Wg1 { get; set; }
    }
}
