//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.Tests.Integration.BusinessLogicLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HwStandardWarranty
    {
        public long Wg { get; set; }
        public Nullable<long> Country { get; set; }
        public long Duration { get; set; }
        public long ReactionTimeId { get; set; }
        public long ReactionTypeId { get; set; }
    
        public virtual Duration Duration1 { get; set; }
        public virtual ReactionTime ReactionTime { get; set; }
        public virtual ReactionType ReactionType { get; set; }
        public virtual Country1 Country1 { get; set; }
        public virtual Wg1 Wg1 { get; set; }
    }
}
