//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.Tests.Integration.BusinessLogicLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManualCost
    {
        public long MatrixId { get; set; }
        public Nullable<double> DealerDiscount { get; set; }
        public Nullable<double> DealerDiscount_Approved { get; set; }
        public Nullable<double> ListPrice { get; set; }
        public Nullable<double> ListPrice_Approved { get; set; }
        public Nullable<double> ServiceTC { get; set; }
        public Nullable<double> ServiceTC_Approved { get; set; }
        public Nullable<double> ServiceTP { get; set; }
        public Nullable<double> ServiceTP_Approved { get; set; }
        public Nullable<double> DealerPrice { get; set; }
        public Nullable<double> DealerPrice_Approved { get; set; }
    
        public virtual Matrix Matrix { get; set; }
    }
}
