//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.Tests.Integration.BusinessLogicLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarkupStandardWaranty
    {
        public long Id { get; set; }
        public long Country { get; set; }
        public long Pla { get; set; }
        public long CentralContractGroup { get; set; }
        public long Wg { get; set; }
        public long ReactionTimeTypeAvailability { get; set; }
        public Nullable<double> MarkupFactorStandardWarranty { get; set; }
        public Nullable<double> MarkupStandardWarranty { get; set; }
        public Nullable<double> MarkupFactorStandardWarranty_Approved { get; set; }
        public Nullable<double> MarkupStandardWarranty_Approved { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<System.DateTime> DeactivatedDateTime { get; set; }
    
        public virtual ReactionTime_ReactionType_Avalability ReactionTime_ReactionType_Avalability { get; set; }
        public virtual CentralContractGroup1 CentralContractGroup1 { get; set; }
        public virtual Country1 Country1 { get; set; }
        public virtual Pla1 Pla1 { get; set; }
        public virtual Wg1 Wg1 { get; set; }
    }
}
