//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.Tests.Integration.BusinessLogicLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarkupStandardWarantyView
    {
        public long Country { get; set; }
        public long Wg { get; set; }
        public Nullable<long> ReactionTimeId { get; set; }
        public Nullable<long> ReactionTypeId { get; set; }
        public Nullable<long> AvailabilityId { get; set; }
        public Nullable<double> MarkupFactorStandardWarranty { get; set; }
        public Nullable<double> MarkupFactorStandardWarranty_Approved { get; set; }
        public Nullable<double> MarkupStandardWarranty { get; set; }
        public Nullable<double> MarkupStandardWarranty_Approved { get; set; }
    }
}
