//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.Tests.Integration.BusinessLogicLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProActiveDigit
    {
        public long Id { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string Description { get; set; }
        public Nullable<long> DigitId { get; set; }
        public string Name { get; set; }
        public string ProActive { get; set; }
        public Nullable<long> ProActiveId { get; set; }
        public string ReactiveMappingDigit { get; set; }
    }
}
