//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.Tests.Integration.BusinessLogicLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProActiveView1
    {
        public long Country { get; set; }
        public long Sog { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<double> LocalPreparation { get; set; }
        public Nullable<double> LocalPreparation_Approved { get; set; }
        public Nullable<double> LocalRegularUpdate { get; set; }
        public Nullable<double> LocalRegularUpdate_Approved { get; set; }
        public Nullable<double> LocalRemoteCustomerBriefing { get; set; }
        public Nullable<double> LocalRemoteCustomerBriefing_Approved { get; set; }
        public Nullable<double> LocalOnsiteCustomerBriefing { get; set; }
        public Nullable<double> LocalOnsiteCustomerBriefing_Approved { get; set; }
        public Nullable<double> Travel { get; set; }
        public Nullable<double> Travel_Approved { get; set; }
        public Nullable<double> CentralExecutionReport { get; set; }
        public Nullable<double> CentralExecutionReport_Approved { get; set; }
        public Nullable<double> Setup { get; set; }
        public Nullable<double> Setup_Approved { get; set; }
        public Nullable<double> Service { get; set; }
        public Nullable<double> Service_Approved { get; set; }
        public Nullable<double> ProActive { get; set; }
        public Nullable<double> ProActive_Approved { get; set; }
    }
}
