//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.Tests.Integration.BusinessLogicLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProlongationMarkup
    {
        public long Id { get; set; }
        public long Country { get; set; }
        public long Pla { get; set; }
        public long Wg { get; set; }
        public long ReactionTimeTypeAvailability { get; set; }
        public Nullable<double> ProlongationMarkupFactor { get; set; }
        public Nullable<double> ProlongationMarkup1 { get; set; }
        public Nullable<double> ProlongationMarkupFactor_Approved { get; set; }
        public Nullable<double> ProlongationMarkup_Approved { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<System.DateTime> DeactivatedDateTime { get; set; }
    
        public virtual ReactionTime_ReactionType_Avalability ReactionTime_ReactionType_Avalability { get; set; }
        public virtual Country Country1 { get; set; }
        public virtual Pla Pla1 { get; set; }
        public virtual Wg Wg1 { get; set; }
    }
}
