//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.Tests.Integration.BusinessLogicLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReactionType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReactionType()
        {
            this.AvailabilityFees = new HashSet<AvailabilityFee>();
            this.ReactionTime_ReactionType = new HashSet<ReactionTime_ReactionType>();
            this.ReactionTime_ReactionType_Avalability = new HashSet<ReactionTime_ReactionType_Avalability>();
            this.HwStandardWarranties = new HashSet<HwStandardWarranty>();
            this.HwFspCodeTranslations = new HashSet<HwFspCodeTranslation>();
            this.LocalPortfolios = new HashSet<LocalPortfolio>();
            this.PrincipalPortfolios = new HashSet<PrincipalPortfolio>();
            this.SwFspCodeTranslations = new HashSet<SwFspCodeTranslation>();
        }
    
        public long Id { get; set; }
        public string ExternalName { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvailabilityFee> AvailabilityFees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReactionTime_ReactionType> ReactionTime_ReactionType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReactionTime_ReactionType_Avalability> ReactionTime_ReactionType_Avalability { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HwStandardWarranty> HwStandardWarranties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HwFspCodeTranslation> HwFspCodeTranslations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocalPortfolio> LocalPortfolios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrincipalPortfolio> PrincipalPortfolios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SwFspCodeTranslation> SwFspCodeTranslations { get; set; }
    }
}
