//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.Tests.Integration.BusinessLogicLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReinsuranceYear
    {
        public long Wg { get; set; }
        public Nullable<double> ReinsuranceFlatfee1 { get; set; }
        public Nullable<double> ReinsuranceFlatfee2 { get; set; }
        public Nullable<double> ReinsuranceFlatfee3 { get; set; }
        public Nullable<double> ReinsuranceFlatfee4 { get; set; }
        public Nullable<double> ReinsuranceFlatfee5 { get; set; }
        public Nullable<double> ReinsuranceFlatfeeP1 { get; set; }
        public Nullable<double> ReinsuranceFlatfee1_Approved { get; set; }
        public Nullable<double> ReinsuranceFlatfee2_Approved { get; set; }
        public Nullable<double> ReinsuranceFlatfee3_Approved { get; set; }
        public Nullable<double> ReinsuranceFlatfee4_Approved { get; set; }
        public Nullable<double> ReinsuranceFlatfee5_Approved { get; set; }
        public Nullable<double> ReinsuranceFlatfeeP1_Approved { get; set; }
        public Nullable<double> ReinsuranceUpliftFactor_NBD_9x5 { get; set; }
        public Nullable<double> ReinsuranceUpliftFactor_4h_9x5 { get; set; }
        public Nullable<double> ReinsuranceUpliftFactor_4h_24x7 { get; set; }
        public Nullable<double> ReinsuranceUpliftFactor_NBD_9x5_Approved { get; set; }
        public Nullable<double> ReinsuranceUpliftFactor_4h_9x5_Approved { get; set; }
        public Nullable<double> ReinsuranceUpliftFactor_4h_24x7_Approved { get; set; }
    
        public virtual Wg1 Wg1 { get; set; }
    }
}
