//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.Tests.Integration.BusinessLogicLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reinsurance
    {
        public long Id { get; set; }
        public long Wg { get; set; }
        public long Year { get; set; }
        public long ReactionTimeAvailability { get; set; }
        public Nullable<long> CurrencyReinsurance { get; set; }
        public Nullable<double> ReinsuranceFlatfee { get; set; }
        public Nullable<double> ReinsuranceUpliftFactor { get; set; }
        public Nullable<long> CurrencyReinsurance_Approved { get; set; }
        public Nullable<double> ReinsuranceFlatfee_Approved { get; set; }
        public Nullable<double> ReinsuranceUpliftFactor_Approved { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<System.DateTime> DeactivatedDateTime { get; set; }
    
        public virtual ReactionTime_Avalability ReactionTime_Avalability { get; set; }
        public virtual Year Year1 { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Currency Currency1 { get; set; }
        public virtual Wg Wg1 { get; set; }
    }
}
