//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.Tests.Integration.BusinessLogicLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReinsuranceView
    {
        public long Wg { get; set; }
        public long Year { get; set; }
        public Nullable<long> AvailabilityId { get; set; }
        public Nullable<long> ReactionTimeId { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<double> Cost_Approved { get; set; }
    }
}
