//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.Tests.Integration.BusinessLogicLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportFilter
    {
        public long Id { get; set; }
        public int Index { get; set; }
        public string Name { get; set; }
        public long ReportId { get; set; }
        public string Text { get; set; }
        public long TypeId { get; set; }
        public string Value { get; set; }
    
        public virtual Report Report { get; set; }
        public virtual ReportFilterType ReportFilterType { get; set; }
    }
}
