//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.Tests.Integration.BusinessLogicLayer.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ScdEntities : DbContext
    {
        public ScdEntities()
            : base("name=ScdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AvailabilityFee> AvailabilityFees { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RolePermission> RolePermissions { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<Availability> Availabilities { get; set; }
        public virtual DbSet<Duration> Durations { get; set; }
        public virtual DbSet<Duration_Availability> Duration_Availability { get; set; }
        public virtual DbSet<ProActiveSla> ProActiveSlas { get; set; }
        public virtual DbSet<ReactionTime> ReactionTimes { get; set; }
        public virtual DbSet<ReactionTime_Avalability> ReactionTime_Avalability { get; set; }
        public virtual DbSet<ReactionTime_ReactionType> ReactionTime_ReactionType { get; set; }
        public virtual DbSet<ReactionTime_ReactionType_Avalability> ReactionTime_ReactionType_Avalability { get; set; }
        public virtual DbSet<ReactionType> ReactionTypes { get; set; }
        public virtual DbSet<ServiceLocation> ServiceLocations { get; set; }
        public virtual DbSet<Year> Years { get; set; }
        public virtual DbSet<HwFspCodeTranslation> HwFspCodeTranslations { get; set; }
        public virtual DbSet<HwHddFspCodeTranslation> HwHddFspCodeTranslations { get; set; }
        public virtual DbSet<SwFspCodeTranslation> SwFspCodeTranslations { get; set; }
        public virtual DbSet<AFR> AFRs { get; set; }
        public virtual DbSet<AfrYear> AfrYears { get; set; }
        public virtual DbSet<AvailabilityFee1> AvailabilityFee1 { get; set; }
        public virtual DbSet<FieldServiceCost> FieldServiceCosts { get; set; }
        public virtual DbSet<HddRetention> HddRetentions { get; set; }
        public virtual DbSet<InstallBase> InstallBases { get; set; }
        public virtual DbSet<LogisticsCost> LogisticsCosts { get; set; }
        public virtual DbSet<ManualCost> ManualCosts { get; set; }
        public virtual DbSet<MarkupOtherCost> MarkupOtherCosts { get; set; }
        public virtual DbSet<MarkupStandardWaranty> MarkupStandardWaranties { get; set; }
        public virtual DbSet<MaterialCostOow> MaterialCostOows { get; set; }
        public virtual DbSet<MaterialCostOowCalc> MaterialCostOowCalcs { get; set; }
        public virtual DbSet<MaterialCostOowEmeia> MaterialCostOowEmeias { get; set; }
        public virtual DbSet<MaterialCostWarranty> MaterialCostWarranties { get; set; }
        public virtual DbSet<ProActive> ProActives { get; set; }
        public virtual DbSet<ProlongationMarkup> ProlongationMarkups { get; set; }
        public virtual DbSet<Reinsurance> Reinsurances { get; set; }
        public virtual DbSet<ReinsuranceYear> ReinsuranceYears { get; set; }
        public virtual DbSet<RoleCodeHourlyRate> RoleCodeHourlyRates { get; set; }
        public virtual DbSet<ServiceSupportCost> ServiceSupportCosts { get; set; }
        public virtual DbSet<TaxAndDuty> TaxAndDuties { get; set; }
        public virtual DbSet<CostBlockHistory> CostBlockHistories { get; set; }
        public virtual DbSet<Hardware_AFR> Hardware_AFR { get; set; }
        public virtual DbSet<Hardware_AvailabilityFee> Hardware_AvailabilityFee { get; set; }
        public virtual DbSet<Hardware_FieldServiceCost> Hardware_FieldServiceCost { get; set; }
        public virtual DbSet<Hardware_HddRetention> Hardware_HddRetention { get; set; }
        public virtual DbSet<Hardware_InstallBase> Hardware_InstallBase { get; set; }
        public virtual DbSet<Hardware_LogisticsCosts> Hardware_LogisticsCosts { get; set; }
        public virtual DbSet<Hardware_MarkupOtherCosts> Hardware_MarkupOtherCosts { get; set; }
        public virtual DbSet<Hardware_MarkupStandardWaranty> Hardware_MarkupStandardWaranty { get; set; }
        public virtual DbSet<Hardware_MaterialCostOow> Hardware_MaterialCostOow { get; set; }
        public virtual DbSet<Hardware_MaterialCostOowEmeia> Hardware_MaterialCostOowEmeia { get; set; }
        public virtual DbSet<Hardware_MaterialCostWarranty> Hardware_MaterialCostWarranty { get; set; }
        public virtual DbSet<Hardware_ProActive> Hardware_ProActive { get; set; }
        public virtual DbSet<Hardware_ProlongationMarkup> Hardware_ProlongationMarkup { get; set; }
        public virtual DbSet<Hardware_Reinsurance> Hardware_Reinsurance { get; set; }
        public virtual DbSet<Hardware_RoleCodeHourlyRates> Hardware_RoleCodeHourlyRates { get; set; }
        public virtual DbSet<Hardware_ServiceSupportCost> Hardware_ServiceSupportCost { get; set; }
        public virtual DbSet<SoftwareSolution_ProActiveSw> SoftwareSolution_ProActiveSw { get; set; }
        public virtual DbSet<SoftwareSolution_SwSpMaintenance> SoftwareSolution_SwSpMaintenance { get; set; }
        public virtual DbSet<Configuration> Configurations { get; set; }
        public virtual DbSet<CentralContractGroup1> CentralContractGroup1 { get; set; }
        public virtual DbSet<ClusterPla1> ClusterPla1 { get; set; }
        public virtual DbSet<ClusterRegion1> ClusterRegion1 { get; set; }
        public virtual DbSet<Country1> Country1 { get; set; }
        public virtual DbSet<CountryGroup> CountryGroups { get; set; }
        public virtual DbSet<Pla1> Pla1 { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<RoleCode1> RoleCode1 { get; set; }
        public virtual DbSet<Sfab1> Sfab1 { get; set; }
        public virtual DbSet<Sog1> Sog1 { get; set; }
        public virtual DbSet<SwDigit1> SwDigit1 { get; set; }
        public virtual DbSet<SwDigitLicense> SwDigitLicenses { get; set; }
        public virtual DbSet<SwLicense> SwLicenses { get; set; }
        public virtual DbSet<Wg1> Wg1 { get; set; }
        public virtual DbSet<LocalPortfolio> LocalPortfolios { get; set; }
        public virtual DbSet<PrincipalPortfolio> PrincipalPortfolios { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<ExchangeRate> ExchangeRates { get; set; }
        public virtual DbSet<CdCsConfiguration> CdCsConfigurations { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<ReportColumn> ReportColumns { get; set; }
        public virtual DbSet<ReportColumnType> ReportColumnTypes { get; set; }
        public virtual DbSet<ReportFilter> ReportFilters { get; set; }
        public virtual DbSet<ReportFilterType> ReportFilterTypes { get; set; }
        public virtual DbSet<ProActiveDigit> ProActiveDigits { get; set; }
        public virtual DbSet<ProActiveSw> ProActiveSws { get; set; }
        public virtual DbSet<SwSpMaintenance> SwSpMaintenances { get; set; }
        public virtual DbSet<JobsSchedule> JobsSchedules { get; set; }
        public virtual DbSet<HwStandardWarranty> HwStandardWarranties { get; set; }
        public virtual DbSet<AvailabilityFeeCalc> AvailabilityFeeCalcs { get; set; }
        public virtual DbSet<Availability1> Availability1 { get; set; }
        public virtual DbSet<CentralContractGroup> CentralContractGroups { get; set; }
        public virtual DbSet<ClusterPla> ClusterPlas { get; set; }
        public virtual DbSet<ClusterRegion> ClusterRegions { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<DurationAvailability> DurationAvailabilities { get; set; }
        public virtual DbSet<EmeiaCountry> EmeiaCountries { get; set; }
        public virtual DbSet<NonEmeiaCountry> NonEmeiaCountries { get; set; }
        public virtual DbSet<Pla> Plas { get; set; }
        public virtual DbSet<ReactionTimeAvailability> ReactionTimeAvailabilities { get; set; }
        public virtual DbSet<ReactionTimeType> ReactionTimeTypes { get; set; }
        public virtual DbSet<ReactionTimeTypeAvailability> ReactionTimeTypeAvailabilities { get; set; }
        public virtual DbSet<RoleCode> RoleCodes { get; set; }
        public virtual DbSet<ServiceLocation1> ServiceLocation1 { get; set; }
        public virtual DbSet<Sfab> Sfabs { get; set; }
        public virtual DbSet<Sog> Sogs { get; set; }
        public virtual DbSet<SwDigit> SwDigits { get; set; }
        public virtual DbSet<Wg> Wgs { get; set; }
        public virtual DbSet<Year1> Year1 { get; set; }
    }
}
