//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.Tests.Integration.BusinessLogicLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceSupportCost
    {
        public long Id { get; set; }
        public long Country { get; set; }
        public long ClusterPla { get; set; }
        public long ClusterRegion { get; set; }
        public Nullable<double> C1stLevelSupportCostsCountry { get; set; }
        public Nullable<double> C2ndLevelSupportCostsClusterRegion { get; set; }
        public Nullable<double> C2ndLevelSupportCostsLocal { get; set; }
        public Nullable<double> C1stLevelSupportCostsCountry_Approved { get; set; }
        public Nullable<double> C2ndLevelSupportCostsClusterRegion_Approved { get; set; }
        public Nullable<double> C2ndLevelSupportCostsLocal_Approved { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<System.DateTime> DeactivatedDateTime { get; set; }
    
        public virtual ClusterPla ClusterPla1 { get; set; }
        public virtual ClusterRegion ClusterRegion1 { get; set; }
        public virtual Country Country1 { get; set; }
    }
}
