//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.Tests.Integration.BusinessLogicLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceCostCalculationView
    {
        public Nullable<long> YearId { get; set; }
        public string Year { get; set; }
        public int YearValue { get; set; }
        public Nullable<long> AvailabilityId { get; set; }
        public string Availability { get; set; }
        public long SogId { get; set; }
        public string Sog { get; set; }
        public string SogDescription { get; set; }
        public string Description { get; set; }
        public Nullable<double> DealerPrice { get; set; }
        public Nullable<double> MaintenanceListPrice { get; set; }
        public Nullable<double> Reinsurance { get; set; }
        public Nullable<double> ServiceSupport { get; set; }
        public Nullable<double> TransferPrice { get; set; }
    }
}
