//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.Tests.Integration.BusinessLogicLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftwareSolution_SwSpMaintenance
    {
        public long Id { get; set; }
        public Nullable<long> Pla { get; set; }
        public Nullable<long> Sfab { get; set; }
        public Nullable<long> Sog { get; set; }
        public Nullable<long> SwDigit { get; set; }
        public Nullable<long> DurationAvailability { get; set; }
        public Nullable<long> Availability { get; set; }
        public Nullable<double> C2ndLevelSupportCosts { get; set; }
        public Nullable<double> InstalledBaseSog { get; set; }
        public Nullable<double> ReinsuranceFlatfee { get; set; }
        public Nullable<long> CurrencyReinsurance { get; set; }
        public Nullable<double> RecommendedSwSpMaintenanceListPrice { get; set; }
        public Nullable<double> MarkupForProductMarginSwLicenseListPrice { get; set; }
        public Nullable<double> ShareSwSpMaintenanceListPrice { get; set; }
        public Nullable<double> DiscountDealerPrice { get; set; }
        public long CostBlockHistory { get; set; }
    
        public virtual Availability Availability1 { get; set; }
        public virtual CostBlockHistory CostBlockHistory1 { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Pla1 Pla1 { get; set; }
        public virtual Sfab1 Sfab1 { get; set; }
        public virtual Sog1 Sog1 { get; set; }
        public virtual SwDigit1 SwDigit1 { get; set; }
    }
}
