//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.Tests.Integration.BusinessLogicLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sog1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sog1()
        {
            this.SwFspCodeTranslations = new HashSet<SwFspCodeTranslation>();
            this.SoftwareSolution_ProActiveSw = new HashSet<SoftwareSolution_ProActiveSw>();
            this.SoftwareSolution_SwSpMaintenance = new HashSet<SoftwareSolution_SwSpMaintenance>();
            this.Sogs = new HashSet<Sog>();
            this.ProActiveSws = new HashSet<ProActiveSw>();
            this.SwSpMaintenances = new HashSet<SwSpMaintenance>();
            this.SwDigit1 = new HashSet<SwDigit1>();
            this.Wg1 = new HashSet<Wg1>();
        }
    
        public long Id { get; set; }
        public string Alignment { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<System.DateTime> DeactivatedDateTime { get; set; }
        public string Description { get; set; }
        public string FabGrp { get; set; }
        public bool IsSoftware { get; set; }
        public System.DateTime ModifiedDateTime { get; set; }
        public string Name { get; set; }
        public long PlaId { get; set; }
        public string SCD_ServiceType { get; set; }
        public Nullable<long> SFabId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SwFspCodeTranslation> SwFspCodeTranslations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftwareSolution_ProActiveSw> SoftwareSolution_ProActiveSw { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftwareSolution_SwSpMaintenance> SoftwareSolution_SwSpMaintenance { get; set; }
        public virtual Pla1 Pla1 { get; set; }
        public virtual Sfab1 Sfab1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sog> Sogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProActiveSw> ProActiveSws { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SwSpMaintenance> SwSpMaintenances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SwDigit1> SwDigit1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wg1> Wg1 { get; set; }
    }
}
