//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.Tests.Integration.BusinessLogicLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SwDigitLicense
    {
        public long Id { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<long> SwDigitId { get; set; }
        public Nullable<long> SwLicenseId { get; set; }
    
        public virtual SwDigit SwDigit { get; set; }
        public virtual SwLicense SwLicense { get; set; }
    }
}
