//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.Tests.Integration.BusinessLogicLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SwSpMaintenanceView
    {
        public long Pla { get; set; }
        public long Sog { get; set; }
        public long Sfab { get; set; }
        public Nullable<long> Year { get; set; }
        public Nullable<long> Availability { get; set; }
        public Nullable<double> C2ndLevelSupportCosts { get; set; }
        public Nullable<double> C2ndLevelSupportCosts_Approved { get; set; }
        public Nullable<double> InstalledBaseSog { get; set; }
        public Nullable<double> InstalledBaseSog_Approved { get; set; }
        public Nullable<double> Reinsurance { get; set; }
        public Nullable<double> Reinsurance_Approved { get; set; }
        public Nullable<double> ShareSwSpMaintenance { get; set; }
        public Nullable<double> ShareSwSpMaintenance_Approved { get; set; }
        public Nullable<double> MaintenanceListPrice { get; set; }
        public Nullable<double> MaintenanceListPrice_Approved { get; set; }
        public Nullable<double> MarkupForProductMargin { get; set; }
        public Nullable<double> MarkupForProductMargin_Approved { get; set; }
        public Nullable<double> DiscountDealerPrice { get; set; }
        public Nullable<double> DiscountDealerPrice_Approved { get; set; }
    }
}
