//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gdc.Scd.Tests.Integration.BusinessLogicLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WgSogView
    {
        public long Id { get; set; }
        public string Alignment { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<System.DateTime> DeactivatedDateTime { get; set; }
        public string Description { get; set; }
        public bool ExistsInLogisticsDb { get; set; }
        public string FabGrp { get; set; }
        public bool IsDeactivatedInLogistic { get; set; }
        public bool IsSoftware { get; set; }
        public System.DateTime ModifiedDateTime { get; set; }
        public string Name { get; set; }
        public long PlaId { get; set; }
        public Nullable<long> RoleCodeId { get; set; }
        public string SCD_ServiceType { get; set; }
        public Nullable<long> SFabId { get; set; }
        public Nullable<long> SogId { get; set; }
        public int WgType { get; set; }
        public string Sog { get; set; }
        public string SogDescription { get; set; }
    }
}
