//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Api.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web.Api.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SCDConfiguration&gt;
        ///  &lt;InputLevels&gt;
        ///    &lt;InputLevel Name=&quot;Country&quot;/&gt;
        ///    &lt;InputLevel Name=&quot;ClusterRegion&quot; Caption=&quot;Region&quot;/&gt;
        ///    &lt;InputLevel Name=&quot;ClusterPla&quot; Caption=&quot;Cluster Pla&quot;/&gt;
        ///    &lt;InputLevel Name=&quot;Pla&quot; Caption=&quot;PLA&quot;/&gt;
        ///    &lt;InputLevel Name=&quot;Sfab&quot; Caption=&quot;SFAB&quot;/&gt;
        ///    &lt;InputLevel Name=&quot;Sog&quot; Caption=&quot;SOG&quot;/&gt;
        ///    &lt;InputLevel Name=&quot;SwDigit&quot; Caption=&quot;SW Level (Digit)&quot;/&gt;
        ///    &lt;InputLevel Name=&quot;SwLicense&quot; Caption=&quot;SW License&quot;/&gt;
        ///    &lt;InputLevel Name=&quot;Wg&quot; Caption=&quot;WG&quot;/&gt;
        ///    
        ///    &lt;Default&gt;
        ///      &lt;Inp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DomainConfig {
            get {
                return ResourceManager.GetString("DomainConfig", resourceCulture);
            }
        }
    }
}
